<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/finalmask/salamander/config.proto

namespace GPBMetadata\Transport\Internet\Finalmask\Salamander;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
±
4transport/internet/finalmask/salamander/config.proto,xray.transport.internet.finalmask.salamander"
Config
password (	B¦
0com.xray.transport.internet.finalmask.salamanderPZAgithub.com/xtls/xray-core/transport/internet/finalmask/salamanderª,Xray.Transport.Internet.Finalmask.Salamanderbproto3'
        , true);

        static::$is_initialized = true;
    }
}

