<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/finalmask/header/wireguard/config.proto

namespace GPBMetadata\Transport\Internet\Finalmask\Header\Wireguard;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
½
:transport/internet/finalmask/header/wireguard/config.proto2xray.transport.internet.finalmask.header.wireguard"
ConfigB¸
6com.xray.transport.internet.finalmask.header.wireguardPZGgithub.com/xtls/xray-core/transport/internet/finalmask/header/wireguardª2Xray.Transport.Internet.Finalmask.Header.Wireguardbproto3'
        , true);

        static::$is_initialized = true;
    }
}

