<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/finalmask/sudoku/config.proto

namespace Xray\Transport\Internet\Finalmask\Sudoku;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.finalmask.sudoku.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string password = 1;</code>
     */
    protected $password = '';
    /**
     * Generated from protobuf field <code>string ascii = 2;</code>
     */
    protected $ascii = '';
    /**
     * Generated from protobuf field <code>string custom_table = 3;</code>
     */
    protected $custom_table = '';
    /**
     * Generated from protobuf field <code>uint32 padding_min = 4;</code>
     */
    protected $padding_min = 0;
    /**
     * Generated from protobuf field <code>uint32 padding_max = 5;</code>
     */
    protected $padding_max = 0;
    /**
     * Generated from protobuf field <code>repeated string custom_tables = 7;</code>
     */
    private $custom_tables;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $password
     *     @type string $ascii
     *     @type string $custom_table
     *     @type int $padding_min
     *     @type int $padding_max
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $custom_tables
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Finalmask\Sudoku\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string password = 1;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ascii = 2;</code>
     * @return string
     */
    public function getAscii()
    {
        return $this->ascii;
    }

    /**
     * Generated from protobuf field <code>string ascii = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAscii($var)
    {
        GPBUtil::checkString($var, True);
        $this->ascii = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string custom_table = 3;</code>
     * @return string
     */
    public function getCustomTable()
    {
        return $this->custom_table;
    }

    /**
     * Generated from protobuf field <code>string custom_table = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomTable($var)
    {
        GPBUtil::checkString($var, True);
        $this->custom_table = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 padding_min = 4;</code>
     * @return int
     */
    public function getPaddingMin()
    {
        return $this->padding_min;
    }

    /**
     * Generated from protobuf field <code>uint32 padding_min = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPaddingMin($var)
    {
        GPBUtil::checkUint32($var);
        $this->padding_min = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 padding_max = 5;</code>
     * @return int
     */
    public function getPaddingMax()
    {
        return $this->padding_max;
    }

    /**
     * Generated from protobuf field <code>uint32 padding_max = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPaddingMax($var)
    {
        GPBUtil::checkUint32($var);
        $this->padding_max = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string custom_tables = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCustomTables()
    {
        return $this->custom_tables;
    }

    /**
     * Generated from protobuf field <code>repeated string custom_tables = 7;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCustomTables($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->custom_tables = $arr;

        return $this;
    }

}

