<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/finalmask/mkcp/original/config.proto

namespace GPBMetadata\Transport\Internet\Finalmask\Mkcp\Original;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
®
7transport/internet/finalmask/mkcp/original/config.proto/xray.transport.internet.finalmask.mkcp.original"
ConfigB¯
3com.xray.transport.internet.finalmask.mkcp.originalPZDgithub.com/xtls/xray-core/transport/internet/finalmask/mkcp/originalª/Xray.Transport.Internet.Finalmask.Mkcp.Originalbproto3'
        , true);

        static::$is_initialized = true;
    }
}

