<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/finalmask/header/dtls/config.proto

namespace GPBMetadata\Transport\Internet\Finalmask\Header\Dtls;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¤
5transport/internet/finalmask/header/dtls/config.proto-xray.transport.internet.finalmask.header.dtls"
ConfigB©
1com.xray.transport.internet.finalmask.header.dtlsPZBgithub.com/xtls/xray-core/transport/internet/finalmask/header/dtlsª-Xray.Transport.Internet.Finalmask.Header.Dtlsbproto3'
        , true);

        static::$is_initialized = true;
    }
}

