<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/reality/config.proto

namespace Xray\Transport\Internet\Reality;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.reality.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool show = 1;</code>
     */
    protected $show = false;
    /**
     * Generated from protobuf field <code>string dest = 2;</code>
     */
    protected $dest = '';
    /**
     * Generated from protobuf field <code>string type = 3;</code>
     */
    protected $type = '';
    /**
     * Generated from protobuf field <code>uint64 xver = 4;</code>
     */
    protected $xver = 0;
    /**
     * Generated from protobuf field <code>repeated string server_names = 5;</code>
     */
    private $server_names;
    /**
     * Generated from protobuf field <code>bytes private_key = 6;</code>
     */
    protected $private_key = '';
    /**
     * Generated from protobuf field <code>bytes min_client_ver = 7;</code>
     */
    protected $min_client_ver = '';
    /**
     * Generated from protobuf field <code>bytes max_client_ver = 8;</code>
     */
    protected $max_client_ver = '';
    /**
     * Generated from protobuf field <code>uint64 max_time_diff = 9;</code>
     */
    protected $max_time_diff = 0;
    /**
     * Generated from protobuf field <code>repeated bytes short_ids = 10;</code>
     */
    private $short_ids;
    /**
     * Generated from protobuf field <code>bytes mldsa65_seed = 11;</code>
     */
    protected $mldsa65_seed = '';
    /**
     * Generated from protobuf field <code>.xray.transport.internet.reality.LimitFallback limit_fallback_upload = 12;</code>
     */
    protected $limit_fallback_upload = null;
    /**
     * Generated from protobuf field <code>.xray.transport.internet.reality.LimitFallback limit_fallback_download = 13;</code>
     */
    protected $limit_fallback_download = null;
    /**
     * Generated from protobuf field <code>string Fingerprint = 21;</code>
     */
    protected $Fingerprint = '';
    /**
     * Generated from protobuf field <code>string server_name = 22;</code>
     */
    protected $server_name = '';
    /**
     * Generated from protobuf field <code>bytes public_key = 23;</code>
     */
    protected $public_key = '';
    /**
     * Generated from protobuf field <code>bytes short_id = 24;</code>
     */
    protected $short_id = '';
    /**
     * Generated from protobuf field <code>bytes mldsa65_verify = 25;</code>
     */
    protected $mldsa65_verify = '';
    /**
     * Generated from protobuf field <code>string spider_x = 26;</code>
     */
    protected $spider_x = '';
    /**
     * Generated from protobuf field <code>repeated int64 spider_y = 27;</code>
     */
    private $spider_y;
    /**
     * Generated from protobuf field <code>string master_key_log = 31;</code>
     */
    protected $master_key_log = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $show
     *     @type string $dest
     *     @type string $type
     *     @type int|string $xver
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $server_names
     *     @type string $private_key
     *     @type string $min_client_ver
     *     @type string $max_client_ver
     *     @type int|string $max_time_diff
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $short_ids
     *     @type string $mldsa65_seed
     *     @type \Xray\Transport\Internet\Reality\LimitFallback $limit_fallback_upload
     *     @type \Xray\Transport\Internet\Reality\LimitFallback $limit_fallback_download
     *     @type string $Fingerprint
     *     @type string $server_name
     *     @type string $public_key
     *     @type string $short_id
     *     @type string $mldsa65_verify
     *     @type string $spider_x
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $spider_y
     *     @type string $master_key_log
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Reality\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool show = 1;</code>
     * @return bool
     */
    public function getShow()
    {
        return $this->show;
    }

    /**
     * Generated from protobuf field <code>bool show = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setShow($var)
    {
        GPBUtil::checkBool($var);
        $this->show = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string dest = 2;</code>
     * @return string
     */
    public function getDest()
    {
        return $this->dest;
    }

    /**
     * Generated from protobuf field <code>string dest = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDest($var)
    {
        GPBUtil::checkString($var, True);
        $this->dest = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string type = 3;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 xver = 4;</code>
     * @return int|string
     */
    public function getXver()
    {
        return $this->xver;
    }

    /**
     * Generated from protobuf field <code>uint64 xver = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setXver($var)
    {
        GPBUtil::checkUint64($var);
        $this->xver = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string server_names = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getServerNames()
    {
        return $this->server_names;
    }

    /**
     * Generated from protobuf field <code>repeated string server_names = 5;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setServerNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->server_names = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes private_key = 6;</code>
     * @return string
     */
    public function getPrivateKey()
    {
        return $this->private_key;
    }

    /**
     * Generated from protobuf field <code>bytes private_key = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPrivateKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->private_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes min_client_ver = 7;</code>
     * @return string
     */
    public function getMinClientVer()
    {
        return $this->min_client_ver;
    }

    /**
     * Generated from protobuf field <code>bytes min_client_ver = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setMinClientVer($var)
    {
        GPBUtil::checkString($var, False);
        $this->min_client_ver = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes max_client_ver = 8;</code>
     * @return string
     */
    public function getMaxClientVer()
    {
        return $this->max_client_ver;
    }

    /**
     * Generated from protobuf field <code>bytes max_client_ver = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setMaxClientVer($var)
    {
        GPBUtil::checkString($var, False);
        $this->max_client_ver = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 max_time_diff = 9;</code>
     * @return int|string
     */
    public function getMaxTimeDiff()
    {
        return $this->max_time_diff;
    }

    /**
     * Generated from protobuf field <code>uint64 max_time_diff = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxTimeDiff($var)
    {
        GPBUtil::checkUint64($var);
        $this->max_time_diff = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes short_ids = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getShortIds()
    {
        return $this->short_ids;
    }

    /**
     * Generated from protobuf field <code>repeated bytes short_ids = 10;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setShortIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->short_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes mldsa65_seed = 11;</code>
     * @return string
     */
    public function getMldsa65Seed()
    {
        return $this->mldsa65_seed;
    }

    /**
     * Generated from protobuf field <code>bytes mldsa65_seed = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setMldsa65Seed($var)
    {
        GPBUtil::checkString($var, False);
        $this->mldsa65_seed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.reality.LimitFallback limit_fallback_upload = 12;</code>
     * @return \Xray\Transport\Internet\Reality\LimitFallback|null
     */
    public function getLimitFallbackUpload()
    {
        return $this->limit_fallback_upload;
    }

    public function hasLimitFallbackUpload()
    {
        return isset($this->limit_fallback_upload);
    }

    public function clearLimitFallbackUpload()
    {
        unset($this->limit_fallback_upload);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.reality.LimitFallback limit_fallback_upload = 12;</code>
     * @param \Xray\Transport\Internet\Reality\LimitFallback $var
     * @return $this
     */
    public function setLimitFallbackUpload($var)
    {
        GPBUtil::checkMessage($var, \Xray\Transport\Internet\Reality\LimitFallback::class);
        $this->limit_fallback_upload = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.reality.LimitFallback limit_fallback_download = 13;</code>
     * @return \Xray\Transport\Internet\Reality\LimitFallback|null
     */
    public function getLimitFallbackDownload()
    {
        return $this->limit_fallback_download;
    }

    public function hasLimitFallbackDownload()
    {
        return isset($this->limit_fallback_download);
    }

    public function clearLimitFallbackDownload()
    {
        unset($this->limit_fallback_download);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.reality.LimitFallback limit_fallback_download = 13;</code>
     * @param \Xray\Transport\Internet\Reality\LimitFallback $var
     * @return $this
     */
    public function setLimitFallbackDownload($var)
    {
        GPBUtil::checkMessage($var, \Xray\Transport\Internet\Reality\LimitFallback::class);
        $this->limit_fallback_download = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Fingerprint = 21;</code>
     * @return string
     */
    public function getFingerprint()
    {
        return $this->Fingerprint;
    }

    /**
     * Generated from protobuf field <code>string Fingerprint = 21;</code>
     * @param string $var
     * @return $this
     */
    public function setFingerprint($var)
    {
        GPBUtil::checkString($var, True);
        $this->Fingerprint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string server_name = 22;</code>
     * @return string
     */
    public function getServerName()
    {
        return $this->server_name;
    }

    /**
     * Generated from protobuf field <code>string server_name = 22;</code>
     * @param string $var
     * @return $this
     */
    public function setServerName($var)
    {
        GPBUtil::checkString($var, True);
        $this->server_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes public_key = 23;</code>
     * @return string
     */
    public function getPublicKey()
    {
        return $this->public_key;
    }

    /**
     * Generated from protobuf field <code>bytes public_key = 23;</code>
     * @param string $var
     * @return $this
     */
    public function setPublicKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->public_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes short_id = 24;</code>
     * @return string
     */
    public function getShortId()
    {
        return $this->short_id;
    }

    /**
     * Generated from protobuf field <code>bytes short_id = 24;</code>
     * @param string $var
     * @return $this
     */
    public function setShortId($var)
    {
        GPBUtil::checkString($var, False);
        $this->short_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes mldsa65_verify = 25;</code>
     * @return string
     */
    public function getMldsa65Verify()
    {
        return $this->mldsa65_verify;
    }

    /**
     * Generated from protobuf field <code>bytes mldsa65_verify = 25;</code>
     * @param string $var
     * @return $this
     */
    public function setMldsa65Verify($var)
    {
        GPBUtil::checkString($var, False);
        $this->mldsa65_verify = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string spider_x = 26;</code>
     * @return string
     */
    public function getSpiderX()
    {
        return $this->spider_x;
    }

    /**
     * Generated from protobuf field <code>string spider_x = 26;</code>
     * @param string $var
     * @return $this
     */
    public function setSpiderX($var)
    {
        GPBUtil::checkString($var, True);
        $this->spider_x = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 spider_y = 27;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpiderY()
    {
        return $this->spider_y;
    }

    /**
     * Generated from protobuf field <code>repeated int64 spider_y = 27;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpiderY($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->spider_y = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string master_key_log = 31;</code>
     * @return string
     */
    public function getMasterKeyLog()
    {
        return $this->master_key_log;
    }

    /**
     * Generated from protobuf field <code>string master_key_log = 31;</code>
     * @param string $var
     * @return $this
     */
    public function setMasterKeyLog($var)
    {
        GPBUtil::checkString($var, True);
        $this->master_key_log = $var;

        return $this;
    }

}

