<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/reality/config.proto

namespace Xray\Transport\Internet\Reality;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.reality.LimitFallback</code>
 */
class LimitFallback extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 after_bytes = 1;</code>
     */
    protected $after_bytes = 0;
    /**
     * Generated from protobuf field <code>uint64 bytes_per_sec = 2;</code>
     */
    protected $bytes_per_sec = 0;
    /**
     * Generated from protobuf field <code>uint64 burst_bytes_per_sec = 3;</code>
     */
    protected $burst_bytes_per_sec = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $after_bytes
     *     @type int|string $bytes_per_sec
     *     @type int|string $burst_bytes_per_sec
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Reality\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 after_bytes = 1;</code>
     * @return int|string
     */
    public function getAfterBytes()
    {
        return $this->after_bytes;
    }

    /**
     * Generated from protobuf field <code>uint64 after_bytes = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAfterBytes($var)
    {
        GPBUtil::checkUint64($var);
        $this->after_bytes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 bytes_per_sec = 2;</code>
     * @return int|string
     */
    public function getBytesPerSec()
    {
        return $this->bytes_per_sec;
    }

    /**
     * Generated from protobuf field <code>uint64 bytes_per_sec = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBytesPerSec($var)
    {
        GPBUtil::checkUint64($var);
        $this->bytes_per_sec = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 burst_bytes_per_sec = 3;</code>
     * @return int|string
     */
    public function getBurstBytesPerSec()
    {
        return $this->burst_bytes_per_sec;
    }

    /**
     * Generated from protobuf field <code>uint64 burst_bytes_per_sec = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBurstBytesPerSec($var)
    {
        GPBUtil::checkUint64($var);
        $this->burst_bytes_per_sec = $var;

        return $this;
    }

}

