<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/freedom/config.proto

namespace Xray\Proxy\Freedom;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.proxy.freedom.FinalRuleConfig</code>
 */
class FinalRuleConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.xray.proxy.freedom.RuleAction action = 1;</code>
     */
    protected $action = 0;
    /**
     * Generated from protobuf field <code>repeated .xray.common.net.Network networks = 2;</code>
     */
    private $networks;
    /**
     * Generated from protobuf field <code>.xray.common.net.PortList port_list = 3;</code>
     */
    protected $port_list = null;
    /**
     * Generated from protobuf field <code>repeated .xray.common.geodata.IPRule ip = 4;</code>
     */
    private $ip;
    /**
     * Generated from protobuf field <code>.xray.proxy.freedom.Range block_delay = 5;</code>
     */
    protected $block_delay = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $action
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $networks
     *     @type \Xray\Common\Net\PortList $port_list
     *     @type array<\Xray\Common\Geodata\IPRule>|\Google\Protobuf\Internal\RepeatedField $ip
     *     @type \Xray\Proxy\Freedom\Range $block_delay
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Freedom\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xray.proxy.freedom.RuleAction action = 1;</code>
     * @return int
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Generated from protobuf field <code>.xray.proxy.freedom.RuleAction action = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkEnum($var, \Xray\Proxy\Freedom\RuleAction::class);
        $this->action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.net.Network networks = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNetworks()
    {
        return $this->networks;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.net.Network networks = 2;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNetworks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Xray\Common\Net\Network::class);
        $this->networks = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.common.net.PortList port_list = 3;</code>
     * @return \Xray\Common\Net\PortList|null
     */
    public function getPortList()
    {
        return $this->port_list;
    }

    public function hasPortList()
    {
        return isset($this->port_list);
    }

    public function clearPortList()
    {
        unset($this->port_list);
    }

    /**
     * Generated from protobuf field <code>.xray.common.net.PortList port_list = 3;</code>
     * @param \Xray\Common\Net\PortList $var
     * @return $this
     */
    public function setPortList($var)
    {
        GPBUtil::checkMessage($var, \Xray\Common\Net\PortList::class);
        $this->port_list = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.geodata.IPRule ip = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.geodata.IPRule ip = 4;</code>
     * @param array<\Xray\Common\Geodata\IPRule>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIp($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Common\Geodata\IPRule::class);
        $this->ip = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.proxy.freedom.Range block_delay = 5;</code>
     * @return \Xray\Proxy\Freedom\Range|null
     */
    public function getBlockDelay()
    {
        return $this->block_delay;
    }

    public function hasBlockDelay()
    {
        return isset($this->block_delay);
    }

    public function clearBlockDelay()
    {
        unset($this->block_delay);
    }

    /**
     * Generated from protobuf field <code>.xray.proxy.freedom.Range block_delay = 5;</code>
     * @param \Xray\Proxy\Freedom\Range $var
     * @return $this
     */
    public function setBlockDelay($var)
    {
        GPBUtil::checkMessage($var, \Xray\Proxy\Freedom\Range::class);
        $this->block_delay = $var;

        return $this;
    }

}

