<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/freedom/config.proto

namespace Xray\Proxy\Freedom;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.proxy.freedom.Range</code>
 */
class Range extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 min = 1;</code>
     */
    protected $min = 0;
    /**
     * Generated from protobuf field <code>uint64 max = 2;</code>
     */
    protected $max = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $min
     *     @type int|string $max
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Freedom\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 min = 1;</code>
     * @return int|string
     */
    public function getMin()
    {
        return $this->min;
    }

    /**
     * Generated from protobuf field <code>uint64 min = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMin($var)
    {
        GPBUtil::checkUint64($var);
        $this->min = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 max = 2;</code>
     * @return int|string
     */
    public function getMax()
    {
        return $this->max;
    }

    /**
     * Generated from protobuf field <code>uint64 max = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMax($var)
    {
        GPBUtil::checkUint64($var);
        $this->max = $var;

        return $this;
    }

}

