<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/freedom/config.proto

namespace Xray\Proxy\Freedom;

use UnexpectedValueException;

/**
 * Protobuf type <code>xray.proxy.freedom.RuleAction</code>
 */
class RuleAction
{
    /**
     * Generated from protobuf enum <code>Allow = 0;</code>
     */
    const Allow = 0;
    /**
     * Generated from protobuf enum <code>Block = 1;</code>
     */
    const Block = 1;

    private static $valueToName = [
        self::Allow => 'Allow',
        self::Block => 'Block',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

