<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/dokodemo/config.proto

namespace Xray\Proxy\Dokodemo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.proxy.dokodemo.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * List of networks that the Dokodemo accepts.
     *
     * Generated from protobuf field <code>repeated .xray.common.net.Network allowed_networks = 7;</code>
     */
    private $allowed_networks;
    /**
     * Generated from protobuf field <code>.xray.common.net.IPOrDomain rewrite_address = 1;</code>
     */
    protected $rewrite_address = null;
    /**
     * Generated from protobuf field <code>uint32 rewrite_port = 2;</code>
     */
    protected $rewrite_port = 0;
    /**
     * Generated from protobuf field <code>map<string, string> port_map = 3;</code>
     */
    private $port_map;
    /**
     * Generated from protobuf field <code>bool follow_redirect = 5;</code>
     */
    protected $follow_redirect = false;
    /**
     * Generated from protobuf field <code>uint32 user_level = 6;</code>
     */
    protected $user_level = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $allowed_networks
     *           List of networks that the Dokodemo accepts.
     *     @type \Xray\Common\Net\IPOrDomain $rewrite_address
     *     @type int $rewrite_port
     *     @type array|\Google\Protobuf\Internal\MapField $port_map
     *     @type bool $follow_redirect
     *     @type int $user_level
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Dokodemo\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * List of networks that the Dokodemo accepts.
     *
     * Generated from protobuf field <code>repeated .xray.common.net.Network allowed_networks = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAllowedNetworks()
    {
        return $this->allowed_networks;
    }

    /**
     * List of networks that the Dokodemo accepts.
     *
     * Generated from protobuf field <code>repeated .xray.common.net.Network allowed_networks = 7;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAllowedNetworks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Xray\Common\Net\Network::class);
        $this->allowed_networks = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.common.net.IPOrDomain rewrite_address = 1;</code>
     * @return \Xray\Common\Net\IPOrDomain|null
     */
    public function getRewriteAddress()
    {
        return $this->rewrite_address;
    }

    public function hasRewriteAddress()
    {
        return isset($this->rewrite_address);
    }

    public function clearRewriteAddress()
    {
        unset($this->rewrite_address);
    }

    /**
     * Generated from protobuf field <code>.xray.common.net.IPOrDomain rewrite_address = 1;</code>
     * @param \Xray\Common\Net\IPOrDomain $var
     * @return $this
     */
    public function setRewriteAddress($var)
    {
        GPBUtil::checkMessage($var, \Xray\Common\Net\IPOrDomain::class);
        $this->rewrite_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 rewrite_port = 2;</code>
     * @return int
     */
    public function getRewritePort()
    {
        return $this->rewrite_port;
    }

    /**
     * Generated from protobuf field <code>uint32 rewrite_port = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRewritePort($var)
    {
        GPBUtil::checkUint32($var);
        $this->rewrite_port = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> port_map = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getPortMap()
    {
        return $this->port_map;
    }

    /**
     * Generated from protobuf field <code>map<string, string> port_map = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setPortMap($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->port_map = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool follow_redirect = 5;</code>
     * @return bool
     */
    public function getFollowRedirect()
    {
        return $this->follow_redirect;
    }

    /**
     * Generated from protobuf field <code>bool follow_redirect = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setFollowRedirect($var)
    {
        GPBUtil::checkBool($var);
        $this->follow_redirect = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 user_level = 6;</code>
     * @return int
     */
    public function getUserLevel()
    {
        return $this->user_level;
    }

    /**
     * Generated from protobuf field <code>uint32 user_level = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setUserLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->user_level = $var;

        return $this;
    }

}

