<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/http/config.proto

namespace Xray\Proxy\Http;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ClientConfig is the protobuf config for HTTP proxy client.
 *
 * Generated from protobuf message <code>xray.proxy.http.ClientConfig</code>
 */
class ClientConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Sever is a list of HTTP server addresses.
     *
     * Generated from protobuf field <code>.xray.common.protocol.ServerEndpoint server = 1;</code>
     */
    protected $server = null;
    /**
     * Generated from protobuf field <code>repeated .xray.proxy.http.Header header = 2;</code>
     */
    private $header;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Xray\Common\Protocol\ServerEndpoint $server
     *           Sever is a list of HTTP server addresses.
     *     @type array<\Xray\Proxy\Http\Header>|\Google\Protobuf\Internal\RepeatedField $header
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Http\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Sever is a list of HTTP server addresses.
     *
     * Generated from protobuf field <code>.xray.common.protocol.ServerEndpoint server = 1;</code>
     * @return \Xray\Common\Protocol\ServerEndpoint|null
     */
    public function getServer()
    {
        return $this->server;
    }

    public function hasServer()
    {
        return isset($this->server);
    }

    public function clearServer()
    {
        unset($this->server);
    }

    /**
     * Sever is a list of HTTP server addresses.
     *
     * Generated from protobuf field <code>.xray.common.protocol.ServerEndpoint server = 1;</code>
     * @param \Xray\Common\Protocol\ServerEndpoint $var
     * @return $this
     */
    public function setServer($var)
    {
        GPBUtil::checkMessage($var, \Xray\Common\Protocol\ServerEndpoint::class);
        $this->server = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.proxy.http.Header header = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.proxy.http.Header header = 2;</code>
     * @param array<\Xray\Proxy\Http\Header>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHeader($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Proxy\Http\Header::class);
        $this->header = $arr;

        return $this;
    }

}

