<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/finalmask/noise/config.proto

namespace Xray\Transport\Internet\Finalmask\Noise;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.finalmask.noise.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 reset_min = 1;</code>
     */
    protected $reset_min = 0;
    /**
     * Generated from protobuf field <code>int64 reset_max = 2;</code>
     */
    protected $reset_max = 0;
    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.finalmask.noise.Item items = 3;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $reset_min
     *     @type int|string $reset_max
     *     @type array<\Xray\Transport\Internet\Finalmask\Noise\Item>|\Google\Protobuf\Internal\RepeatedField $items
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Finalmask\Noise\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 reset_min = 1;</code>
     * @return int|string
     */
    public function getResetMin()
    {
        return $this->reset_min;
    }

    /**
     * Generated from protobuf field <code>int64 reset_min = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setResetMin($var)
    {
        GPBUtil::checkInt64($var);
        $this->reset_min = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 reset_max = 2;</code>
     * @return int|string
     */
    public function getResetMax()
    {
        return $this->reset_max;
    }

    /**
     * Generated from protobuf field <code>int64 reset_max = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setResetMax($var)
    {
        GPBUtil::checkInt64($var);
        $this->reset_max = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.finalmask.noise.Item items = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.finalmask.noise.Item items = 3;</code>
     * @param array<\Xray\Transport\Internet\Finalmask\Noise\Item>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Transport\Internet\Finalmask\Noise\Item::class);
        $this->items = $arr;

        return $this;
    }

}

