<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/finalmask/noise/config.proto

namespace Xray\Transport\Internet\Finalmask\Noise;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.finalmask.noise.Item</code>
 */
class Item extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 rand_min = 1;</code>
     */
    protected $rand_min = 0;
    /**
     * Generated from protobuf field <code>int64 rand_max = 2;</code>
     */
    protected $rand_max = 0;
    /**
     * Generated from protobuf field <code>int32 rand_range_min = 3;</code>
     */
    protected $rand_range_min = 0;
    /**
     * Generated from protobuf field <code>int32 rand_range_max = 4;</code>
     */
    protected $rand_range_max = 0;
    /**
     * Generated from protobuf field <code>bytes packet = 5;</code>
     */
    protected $packet = '';
    /**
     * Generated from protobuf field <code>int64 delay_min = 6;</code>
     */
    protected $delay_min = 0;
    /**
     * Generated from protobuf field <code>int64 delay_max = 7;</code>
     */
    protected $delay_max = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $rand_min
     *     @type int|string $rand_max
     *     @type int $rand_range_min
     *     @type int $rand_range_max
     *     @type string $packet
     *     @type int|string $delay_min
     *     @type int|string $delay_max
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Finalmask\Noise\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 rand_min = 1;</code>
     * @return int|string
     */
    public function getRandMin()
    {
        return $this->rand_min;
    }

    /**
     * Generated from protobuf field <code>int64 rand_min = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRandMin($var)
    {
        GPBUtil::checkInt64($var);
        $this->rand_min = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 rand_max = 2;</code>
     * @return int|string
     */
    public function getRandMax()
    {
        return $this->rand_max;
    }

    /**
     * Generated from protobuf field <code>int64 rand_max = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRandMax($var)
    {
        GPBUtil::checkInt64($var);
        $this->rand_max = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 rand_range_min = 3;</code>
     * @return int
     */
    public function getRandRangeMin()
    {
        return $this->rand_range_min;
    }

    /**
     * Generated from protobuf field <code>int32 rand_range_min = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setRandRangeMin($var)
    {
        GPBUtil::checkInt32($var);
        $this->rand_range_min = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 rand_range_max = 4;</code>
     * @return int
     */
    public function getRandRangeMax()
    {
        return $this->rand_range_max;
    }

    /**
     * Generated from protobuf field <code>int32 rand_range_max = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setRandRangeMax($var)
    {
        GPBUtil::checkInt32($var);
        $this->rand_range_max = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes packet = 5;</code>
     * @return string
     */
    public function getPacket()
    {
        return $this->packet;
    }

    /**
     * Generated from protobuf field <code>bytes packet = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPacket($var)
    {
        GPBUtil::checkString($var, False);
        $this->packet = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 delay_min = 6;</code>
     * @return int|string
     */
    public function getDelayMin()
    {
        return $this->delay_min;
    }

    /**
     * Generated from protobuf field <code>int64 delay_min = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDelayMin($var)
    {
        GPBUtil::checkInt64($var);
        $this->delay_min = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 delay_max = 7;</code>
     * @return int|string
     */
    public function getDelayMax()
    {
        return $this->delay_max;
    }

    /**
     * Generated from protobuf field <code>int64 delay_max = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDelayMax($var)
    {
        GPBUtil::checkInt64($var);
        $this->delay_max = $var;

        return $this;
    }

}

