<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/vless/inbound/config.proto

namespace Xray\Proxy\Vless\Inbound;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.proxy.vless.inbound.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .xray.common.protocol.User users = 1;</code>
     */
    private $users;
    /**
     * Generated from protobuf field <code>repeated .xray.proxy.vless.inbound.Fallback fallbacks = 2;</code>
     */
    private $fallbacks;
    /**
     * Generated from protobuf field <code>string decryption = 3;</code>
     */
    protected $decryption = '';
    /**
     * Generated from protobuf field <code>uint32 xorMode = 4;</code>
     */
    protected $xorMode = 0;
    /**
     * Generated from protobuf field <code>int64 seconds_from = 5;</code>
     */
    protected $seconds_from = 0;
    /**
     * Generated from protobuf field <code>int64 seconds_to = 6;</code>
     */
    protected $seconds_to = 0;
    /**
     * Generated from protobuf field <code>string padding = 7;</code>
     */
    protected $padding = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Xray\Common\Protocol\User>|\Google\Protobuf\Internal\RepeatedField $users
     *     @type array<\Xray\Proxy\Vless\Inbound\Fallback>|\Google\Protobuf\Internal\RepeatedField $fallbacks
     *     @type string $decryption
     *     @type int $xorMode
     *     @type int|string $seconds_from
     *     @type int|string $seconds_to
     *     @type string $padding
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Vless\Inbound\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.protocol.User users = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUsers()
    {
        return $this->users;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.protocol.User users = 1;</code>
     * @param array<\Xray\Common\Protocol\User>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUsers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Common\Protocol\User::class);
        $this->users = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.proxy.vless.inbound.Fallback fallbacks = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFallbacks()
    {
        return $this->fallbacks;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.proxy.vless.inbound.Fallback fallbacks = 2;</code>
     * @param array<\Xray\Proxy\Vless\Inbound\Fallback>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFallbacks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Proxy\Vless\Inbound\Fallback::class);
        $this->fallbacks = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string decryption = 3;</code>
     * @return string
     */
    public function getDecryption()
    {
        return $this->decryption;
    }

    /**
     * Generated from protobuf field <code>string decryption = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDecryption($var)
    {
        GPBUtil::checkString($var, True);
        $this->decryption = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 xorMode = 4;</code>
     * @return int
     */
    public function getXorMode()
    {
        return $this->xorMode;
    }

    /**
     * Generated from protobuf field <code>uint32 xorMode = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setXorMode($var)
    {
        GPBUtil::checkUint32($var);
        $this->xorMode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 seconds_from = 5;</code>
     * @return int|string
     */
    public function getSecondsFrom()
    {
        return $this->seconds_from;
    }

    /**
     * Generated from protobuf field <code>int64 seconds_from = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSecondsFrom($var)
    {
        GPBUtil::checkInt64($var);
        $this->seconds_from = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 seconds_to = 6;</code>
     * @return int|string
     */
    public function getSecondsTo()
    {
        return $this->seconds_to;
    }

    /**
     * Generated from protobuf field <code>int64 seconds_to = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSecondsTo($var)
    {
        GPBUtil::checkInt64($var);
        $this->seconds_to = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string padding = 7;</code>
     * @return string
     */
    public function getPadding()
    {
        return $this->padding;
    }

    /**
     * Generated from protobuf field <code>string padding = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setPadding($var)
    {
        GPBUtil::checkString($var, True);
        $this->padding = $var;

        return $this;
    }

}

