<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/finalmask/header/wechat/config.proto

namespace GPBMetadata\Transport\Internet\Finalmask\Header\Wechat;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
®
7transport/internet/finalmask/header/wechat/config.proto/xray.transport.internet.finalmask.header.wechat"
ConfigB¯
3com.xray.transport.internet.finalmask.header.wechatPZDgithub.com/xtls/xray-core/transport/internet/finalmask/header/wechatª/Xray.Transport.Internet.Finalmask.Header.Wechatbproto3'
        , true);

        static::$is_initialized = true;
    }
}

