<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/tun/config.proto

namespace Xray\Proxy\Tun;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.proxy.tun.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>uint32 MTU = 2;</code>
     */
    protected $MTU = 0;
    /**
     * Generated from protobuf field <code>repeated string gateway = 3;</code>
     */
    private $gateway;
    /**
     * Generated from protobuf field <code>repeated string DNS = 4;</code>
     */
    private $DNS;
    /**
     * Generated from protobuf field <code>uint32 user_level = 5;</code>
     */
    protected $user_level = 0;
    /**
     * Generated from protobuf field <code>repeated string auto_system_routing_table = 6;</code>
     */
    private $auto_system_routing_table;
    /**
     * Generated from protobuf field <code>string auto_outbounds_interface = 7;</code>
     */
    protected $auto_outbounds_interface = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type int $MTU
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $gateway
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $DNS
     *     @type int $user_level
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $auto_system_routing_table
     *     @type string $auto_outbounds_interface
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Tun\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 MTU = 2;</code>
     * @return int
     */
    public function getMTU()
    {
        return $this->MTU;
    }

    /**
     * Generated from protobuf field <code>uint32 MTU = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMTU($var)
    {
        GPBUtil::checkUint32($var);
        $this->MTU = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string gateway = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGateway()
    {
        return $this->gateway;
    }

    /**
     * Generated from protobuf field <code>repeated string gateway = 3;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGateway($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->gateway = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string DNS = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDNS()
    {
        return $this->DNS;
    }

    /**
     * Generated from protobuf field <code>repeated string DNS = 4;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDNS($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->DNS = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 user_level = 5;</code>
     * @return int
     */
    public function getUserLevel()
    {
        return $this->user_level;
    }

    /**
     * Generated from protobuf field <code>uint32 user_level = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setUserLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->user_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string auto_system_routing_table = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAutoSystemRoutingTable()
    {
        return $this->auto_system_routing_table;
    }

    /**
     * Generated from protobuf field <code>repeated string auto_system_routing_table = 6;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAutoSystemRoutingTable($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->auto_system_routing_table = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string auto_outbounds_interface = 7;</code>
     * @return string
     */
    public function getAutoOutboundsInterface()
    {
        return $this->auto_outbounds_interface;
    }

    /**
     * Generated from protobuf field <code>string auto_outbounds_interface = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAutoOutboundsInterface($var)
    {
        GPBUtil::checkString($var, True);
        $this->auto_outbounds_interface = $var;

        return $this;
    }

}

