<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/geodata/geodat.proto

namespace Xray\Common\Geodata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.common.geodata.CIDRRule</code>
 */
class CIDRRule extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.xray.common.geodata.CIDR cidr = 1;</code>
     */
    protected $cidr = null;
    /**
     * Generated from protobuf field <code>bool reverse_match = 2;</code>
     */
    protected $reverse_match = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Xray\Common\Geodata\CIDR $cidr
     *     @type bool $reverse_match
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Geodata\Geodat::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xray.common.geodata.CIDR cidr = 1;</code>
     * @return \Xray\Common\Geodata\CIDR|null
     */
    public function getCidr()
    {
        return $this->cidr;
    }

    public function hasCidr()
    {
        return isset($this->cidr);
    }

    public function clearCidr()
    {
        unset($this->cidr);
    }

    /**
     * Generated from protobuf field <code>.xray.common.geodata.CIDR cidr = 1;</code>
     * @param \Xray\Common\Geodata\CIDR $var
     * @return $this
     */
    public function setCidr($var)
    {
        GPBUtil::checkMessage($var, \Xray\Common\Geodata\CIDR::class);
        $this->cidr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool reverse_match = 2;</code>
     * @return bool
     */
    public function getReverseMatch()
    {
        return $this->reverse_match;
    }

    /**
     * Generated from protobuf field <code>bool reverse_match = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setReverseMatch($var)
    {
        GPBUtil::checkBool($var);
        $this->reverse_match = $var;

        return $this;
    }

}

