<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/geodata/geodat.proto

namespace Xray\Common\Geodata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.common.geodata.Domain</code>
 */
class Domain extends \Google\Protobuf\Internal\Message
{
    /**
     * Domain matching type.
     *
     * Generated from protobuf field <code>.xray.common.geodata.Domain.Type type = 1;</code>
     */
    protected $type = 0;
    /**
     * Domain value.
     *
     * Generated from protobuf field <code>string value = 2;</code>
     */
    protected $value = '';
    /**
     * Attributes of this domain. May be used for filtering.
     *
     * Generated from protobuf field <code>repeated .xray.common.geodata.Domain.Attribute attribute = 3;</code>
     */
    private $attribute;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *           Domain matching type.
     *     @type string $value
     *           Domain value.
     *     @type array<\Xray\Common\Geodata\Domain\Attribute>|\Google\Protobuf\Internal\RepeatedField $attribute
     *           Attributes of this domain. May be used for filtering.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Geodata\Geodat::initOnce();
        parent::__construct($data);
    }

    /**
     * Domain matching type.
     *
     * Generated from protobuf field <code>.xray.common.geodata.Domain.Type type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Domain matching type.
     *
     * Generated from protobuf field <code>.xray.common.geodata.Domain.Type type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Xray\Common\Geodata\Domain\Type::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Domain value.
     *
     * Generated from protobuf field <code>string value = 2;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Domain value.
     *
     * Generated from protobuf field <code>string value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

    /**
     * Attributes of this domain. May be used for filtering.
     *
     * Generated from protobuf field <code>repeated .xray.common.geodata.Domain.Attribute attribute = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttribute()
    {
        return $this->attribute;
    }

    /**
     * Attributes of this domain. May be used for filtering.
     *
     * Generated from protobuf field <code>repeated .xray.common.geodata.Domain.Attribute attribute = 3;</code>
     * @param array<\Xray\Common\Geodata\Domain\Attribute>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttribute($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Common\Geodata\Domain\Attribute::class);
        $this->attribute = $arr;

        return $this;
    }

}

