<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/geodata/geodat.proto

namespace Xray\Common\Geodata;

if (false) {
    /**
     * This class is deprecated. Use Xray\Common\Geodata\Domain\Type instead.
     * @deprecated
     */
    class Domain_Type {}
}
class_exists(Domain\Type::class);
@trigger_error('Xray\Common\Geodata\Domain_Type is deprecated and will be removed in the next major release. Use Xray\Common\Geodata\Domain\Type instead', E_USER_DEPRECATED);

