<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/geodata/geodat.proto

namespace Xray\Common\Geodata;

if (false) {
    /**
     * This class is deprecated. Use Xray\Common\Geodata\Domain\Attribute instead.
     * @deprecated
     */
    class Domain_Attribute {}
}
class_exists(Domain\Attribute::class);
@trigger_error('Xray\Common\Geodata\Domain_Attribute is deprecated and will be removed in the next major release. Use Xray\Common\Geodata\Domain\Attribute instead', E_USER_DEPRECATED);

