<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/geodata/geodat.proto

namespace Xray\Common\Geodata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.common.geodata.DomainRule</code>
 */
class DomainRule extends \Google\Protobuf\Internal\Message
{
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Xray\Common\Geodata\GeoSiteRule $geosite
     *     @type \Xray\Common\Geodata\Domain $custom
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Geodata\Geodat::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xray.common.geodata.GeoSiteRule geosite = 1;</code>
     * @return \Xray\Common\Geodata\GeoSiteRule|null
     */
    public function getGeosite()
    {
        return $this->readOneof(1);
    }

    public function hasGeosite()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.xray.common.geodata.GeoSiteRule geosite = 1;</code>
     * @param \Xray\Common\Geodata\GeoSiteRule $var
     * @return $this
     */
    public function setGeosite($var)
    {
        GPBUtil::checkMessage($var, \Xray\Common\Geodata\GeoSiteRule::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.common.geodata.Domain custom = 2;</code>
     * @return \Xray\Common\Geodata\Domain|null
     */
    public function getCustom()
    {
        return $this->readOneof(2);
    }

    public function hasCustom()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.xray.common.geodata.Domain custom = 2;</code>
     * @param \Xray\Common\Geodata\Domain $var
     * @return $this
     */
    public function setCustom($var)
    {
        GPBUtil::checkMessage($var, \Xray\Common\Geodata\Domain::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

