<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/geodata/geodat.proto

namespace Xray\Common\Geodata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.common.geodata.GeoIP</code>
 */
class GeoIP extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string code = 1;</code>
     */
    protected $code = '';
    /**
     * Generated from protobuf field <code>repeated .xray.common.geodata.CIDR cidr = 2;</code>
     */
    private $cidr;
    /**
     * Generated from protobuf field <code>bool reverse_match = 3;</code>
     */
    protected $reverse_match = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $code
     *     @type array<\Xray\Common\Geodata\CIDR>|\Google\Protobuf\Internal\RepeatedField $cidr
     *     @type bool $reverse_match
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Geodata\Geodat::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string code = 1;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>string code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.geodata.CIDR cidr = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCidr()
    {
        return $this->cidr;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.geodata.CIDR cidr = 2;</code>
     * @param array<\Xray\Common\Geodata\CIDR>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCidr($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Common\Geodata\CIDR::class);
        $this->cidr = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool reverse_match = 3;</code>
     * @return bool
     */
    public function getReverseMatch()
    {
        return $this->reverse_match;
    }

    /**
     * Generated from protobuf field <code>bool reverse_match = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setReverseMatch($var)
    {
        GPBUtil::checkBool($var);
        $this->reverse_match = $var;

        return $this;
    }

}

