<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/geodata/geodat.proto

namespace Xray\Common\Geodata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.common.geodata.GeoSite</code>
 */
class GeoSite extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string code = 1;</code>
     */
    protected $code = '';
    /**
     * Generated from protobuf field <code>repeated .xray.common.geodata.Domain domain = 2;</code>
     */
    private $domain;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $code
     *     @type array<\Xray\Common\Geodata\Domain>|\Google\Protobuf\Internal\RepeatedField $domain
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Geodata\Geodat::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string code = 1;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>string code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.geodata.Domain domain = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDomain()
    {
        return $this->domain;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.geodata.Domain domain = 2;</code>
     * @param array<\Xray\Common\Geodata\Domain>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDomain($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Common\Geodata\Domain::class);
        $this->domain = $arr;

        return $this;
    }

}

