<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/geodata/geodat.proto

namespace Xray\Common\Geodata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.common.geodata.GeoSiteList</code>
 */
class GeoSiteList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .xray.common.geodata.GeoSite entry = 1;</code>
     */
    private $entry;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Xray\Common\Geodata\GeoSite>|\Google\Protobuf\Internal\RepeatedField $entry
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Geodata\Geodat::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.geodata.GeoSite entry = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEntry()
    {
        return $this->entry;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.geodata.GeoSite entry = 1;</code>
     * @param array<\Xray\Common\Geodata\GeoSite>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEntry($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Common\Geodata\GeoSite::class);
        $this->entry = $arr;

        return $this;
    }

}

