<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/geodata/geodat.proto

namespace Xray\Common\Geodata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.common.geodata.IPRule</code>
 */
class IPRule extends \Google\Protobuf\Internal\Message
{
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Xray\Common\Geodata\GeoIPRule $geoip
     *     @type \Xray\Common\Geodata\CIDRRule $custom
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Geodata\Geodat::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xray.common.geodata.GeoIPRule geoip = 1;</code>
     * @return \Xray\Common\Geodata\GeoIPRule|null
     */
    public function getGeoip()
    {
        return $this->readOneof(1);
    }

    public function hasGeoip()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.xray.common.geodata.GeoIPRule geoip = 1;</code>
     * @param \Xray\Common\Geodata\GeoIPRule $var
     * @return $this
     */
    public function setGeoip($var)
    {
        GPBUtil::checkMessage($var, \Xray\Common\Geodata\GeoIPRule::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.common.geodata.CIDRRule custom = 2;</code>
     * @return \Xray\Common\Geodata\CIDRRule|null
     */
    public function getCustom()
    {
        return $this->readOneof(2);
    }

    public function hasCustom()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.xray.common.geodata.CIDRRule custom = 2;</code>
     * @param \Xray\Common\Geodata\CIDRRule $var
     * @return $this
     */
    public function setCustom($var)
    {
        GPBUtil::checkMessage($var, \Xray\Common\Geodata\CIDRRule::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

