<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/geodata/config.proto

namespace Xray\App\Geodata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.app.geodata.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string cron = 1;</code>
     */
    protected $cron = '';
    /**
     * Generated from protobuf field <code>string outbound = 2;</code>
     */
    protected $outbound = '';
    /**
     * Generated from protobuf field <code>repeated .xray.app.geodata.Asset assets = 3;</code>
     */
    private $assets;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $cron
     *     @type string $outbound
     *     @type array<\Xray\App\Geodata\Asset>|\Google\Protobuf\Internal\RepeatedField $assets
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Geodata\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string cron = 1;</code>
     * @return string
     */
    public function getCron()
    {
        return $this->cron;
    }

    /**
     * Generated from protobuf field <code>string cron = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCron($var)
    {
        GPBUtil::checkString($var, True);
        $this->cron = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string outbound = 2;</code>
     * @return string
     */
    public function getOutbound()
    {
        return $this->outbound;
    }

    /**
     * Generated from protobuf field <code>string outbound = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOutbound($var)
    {
        GPBUtil::checkString($var, True);
        $this->outbound = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.app.geodata.Asset assets = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAssets()
    {
        return $this->assets;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.app.geodata.Asset assets = 3;</code>
     * @param array<\Xray\App\Geodata\Asset>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAssets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\App\Geodata\Asset::class);
        $this->assets = $arr;

        return $this;
    }

}

