<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/dns/config.proto

namespace Xray\App\Dns;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.app.dns.NameServer</code>
 */
class NameServer extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.xray.common.net.Endpoint address = 1;</code>
     */
    protected $address = null;
    /**
     * Generated from protobuf field <code>bytes client_ip = 5;</code>
     */
    protected $client_ip = '';
    /**
     * Generated from protobuf field <code>bool skipFallback = 6;</code>
     */
    protected $skipFallback = false;
    /**
     * Generated from protobuf field <code>repeated .xray.common.geodata.DomainRule domain = 2;</code>
     */
    private $domain;
    /**
     * Generated from protobuf field <code>repeated .xray.common.geodata.IPRule expected_ip = 3;</code>
     */
    private $expected_ip;
    /**
     * Generated from protobuf field <code>.xray.app.dns.QueryStrategy query_strategy = 7;</code>
     */
    protected $query_strategy = 0;
    /**
     * Generated from protobuf field <code>bool actPrior = 8;</code>
     */
    protected $actPrior = false;
    /**
     * Generated from protobuf field <code>string tag = 9;</code>
     */
    protected $tag = '';
    /**
     * Generated from protobuf field <code>uint64 timeoutMs = 10;</code>
     */
    protected $timeoutMs = 0;
    /**
     * Generated from protobuf field <code>optional bool disableCache = 11;</code>
     */
    protected $disableCache = null;
    /**
     * Generated from protobuf field <code>optional bool serveStale = 15;</code>
     */
    protected $serveStale = null;
    /**
     * Generated from protobuf field <code>optional uint32 serveExpiredTTL = 16;</code>
     */
    protected $serveExpiredTTL = null;
    /**
     * Generated from protobuf field <code>bool finalQuery = 12;</code>
     */
    protected $finalQuery = false;
    /**
     * Generated from protobuf field <code>repeated .xray.common.geodata.IPRule unexpected_ip = 13;</code>
     */
    private $unexpected_ip;
    /**
     * Generated from protobuf field <code>bool actUnprior = 14;</code>
     */
    protected $actUnprior = false;
    /**
     * Generated from protobuf field <code>uint32 policyID = 17;</code>
     */
    protected $policyID = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Xray\Common\Net\Endpoint $address
     *     @type string $client_ip
     *     @type bool $skipFallback
     *     @type array<\Xray\Common\Geodata\DomainRule>|\Google\Protobuf\Internal\RepeatedField $domain
     *     @type array<\Xray\Common\Geodata\IPRule>|\Google\Protobuf\Internal\RepeatedField $expected_ip
     *     @type int $query_strategy
     *     @type bool $actPrior
     *     @type string $tag
     *     @type int|string $timeoutMs
     *     @type bool $disableCache
     *     @type bool $serveStale
     *     @type int $serveExpiredTTL
     *     @type bool $finalQuery
     *     @type array<\Xray\Common\Geodata\IPRule>|\Google\Protobuf\Internal\RepeatedField $unexpected_ip
     *     @type bool $actUnprior
     *     @type int $policyID
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Dns\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xray.common.net.Endpoint address = 1;</code>
     * @return \Xray\Common\Net\Endpoint|null
     */
    public function getAddress()
    {
        return $this->address;
    }

    public function hasAddress()
    {
        return isset($this->address);
    }

    public function clearAddress()
    {
        unset($this->address);
    }

    /**
     * Generated from protobuf field <code>.xray.common.net.Endpoint address = 1;</code>
     * @param \Xray\Common\Net\Endpoint $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, \Xray\Common\Net\Endpoint::class);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes client_ip = 5;</code>
     * @return string
     */
    public function getClientIp()
    {
        return $this->client_ip;
    }

    /**
     * Generated from protobuf field <code>bytes client_ip = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setClientIp($var)
    {
        GPBUtil::checkString($var, False);
        $this->client_ip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool skipFallback = 6;</code>
     * @return bool
     */
    public function getSkipFallback()
    {
        return $this->skipFallback;
    }

    /**
     * Generated from protobuf field <code>bool skipFallback = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setSkipFallback($var)
    {
        GPBUtil::checkBool($var);
        $this->skipFallback = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.geodata.DomainRule domain = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDomain()
    {
        return $this->domain;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.geodata.DomainRule domain = 2;</code>
     * @param array<\Xray\Common\Geodata\DomainRule>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDomain($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Common\Geodata\DomainRule::class);
        $this->domain = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.geodata.IPRule expected_ip = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getExpectedIp()
    {
        return $this->expected_ip;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.geodata.IPRule expected_ip = 3;</code>
     * @param array<\Xray\Common\Geodata\IPRule>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setExpectedIp($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Common\Geodata\IPRule::class);
        $this->expected_ip = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.app.dns.QueryStrategy query_strategy = 7;</code>
     * @return int
     */
    public function getQueryStrategy()
    {
        return $this->query_strategy;
    }

    /**
     * Generated from protobuf field <code>.xray.app.dns.QueryStrategy query_strategy = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setQueryStrategy($var)
    {
        GPBUtil::checkEnum($var, \Xray\App\Dns\QueryStrategy::class);
        $this->query_strategy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool actPrior = 8;</code>
     * @return bool
     */
    public function getActPrior()
    {
        return $this->actPrior;
    }

    /**
     * Generated from protobuf field <code>bool actPrior = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setActPrior($var)
    {
        GPBUtil::checkBool($var);
        $this->actPrior = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tag = 9;</code>
     * @return string
     */
    public function getTag()
    {
        return $this->tag;
    }

    /**
     * Generated from protobuf field <code>string tag = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->tag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 timeoutMs = 10;</code>
     * @return int|string
     */
    public function getTimeoutMs()
    {
        return $this->timeoutMs;
    }

    /**
     * Generated from protobuf field <code>uint64 timeoutMs = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimeoutMs($var)
    {
        GPBUtil::checkUint64($var);
        $this->timeoutMs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool disableCache = 11;</code>
     * @return bool
     */
    public function getDisableCache()
    {
        return isset($this->disableCache) ? $this->disableCache : false;
    }

    public function hasDisableCache()
    {
        return isset($this->disableCache);
    }

    public function clearDisableCache()
    {
        unset($this->disableCache);
    }

    /**
     * Generated from protobuf field <code>optional bool disableCache = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setDisableCache($var)
    {
        GPBUtil::checkBool($var);
        $this->disableCache = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool serveStale = 15;</code>
     * @return bool
     */
    public function getServeStale()
    {
        return isset($this->serveStale) ? $this->serveStale : false;
    }

    public function hasServeStale()
    {
        return isset($this->serveStale);
    }

    public function clearServeStale()
    {
        unset($this->serveStale);
    }

    /**
     * Generated from protobuf field <code>optional bool serveStale = 15;</code>
     * @param bool $var
     * @return $this
     */
    public function setServeStale($var)
    {
        GPBUtil::checkBool($var);
        $this->serveStale = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 serveExpiredTTL = 16;</code>
     * @return int
     */
    public function getServeExpiredTTL()
    {
        return isset($this->serveExpiredTTL) ? $this->serveExpiredTTL : 0;
    }

    public function hasServeExpiredTTL()
    {
        return isset($this->serveExpiredTTL);
    }

    public function clearServeExpiredTTL()
    {
        unset($this->serveExpiredTTL);
    }

    /**
     * Generated from protobuf field <code>optional uint32 serveExpiredTTL = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setServeExpiredTTL($var)
    {
        GPBUtil::checkUint32($var);
        $this->serveExpiredTTL = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool finalQuery = 12;</code>
     * @return bool
     */
    public function getFinalQuery()
    {
        return $this->finalQuery;
    }

    /**
     * Generated from protobuf field <code>bool finalQuery = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setFinalQuery($var)
    {
        GPBUtil::checkBool($var);
        $this->finalQuery = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.geodata.IPRule unexpected_ip = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUnexpectedIp()
    {
        return $this->unexpected_ip;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.geodata.IPRule unexpected_ip = 13;</code>
     * @param array<\Xray\Common\Geodata\IPRule>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUnexpectedIp($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Common\Geodata\IPRule::class);
        $this->unexpected_ip = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool actUnprior = 14;</code>
     * @return bool
     */
    public function getActUnprior()
    {
        return $this->actUnprior;
    }

    /**
     * Generated from protobuf field <code>bool actUnprior = 14;</code>
     * @param bool $var
     * @return $this
     */
    public function setActUnprior($var)
    {
        GPBUtil::checkBool($var);
        $this->actUnprior = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 policyID = 17;</code>
     * @return int
     */
    public function getPolicyID()
    {
        return $this->policyID;
    }

    /**
     * Generated from protobuf field <code>uint32 policyID = 17;</code>
     * @param int $var
     * @return $this
     */
    public function setPolicyID($var)
    {
        GPBUtil::checkUint32($var);
        $this->policyID = $var;

        return $this;
    }

}

