<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/splithttp/config.proto

namespace Xray\Transport\Internet\Splithttp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.splithttp.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string host = 1;</code>
     */
    protected $host = '';
    /**
     * Generated from protobuf field <code>string path = 2;</code>
     */
    protected $path = '';
    /**
     * Generated from protobuf field <code>string mode = 3;</code>
     */
    protected $mode = '';
    /**
     * Generated from protobuf field <code>map<string, string> headers = 4;</code>
     */
    private $headers;
    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig xPaddingBytes = 5;</code>
     */
    protected $xPaddingBytes = null;
    /**
     * Generated from protobuf field <code>bool noGRPCHeader = 6;</code>
     */
    protected $noGRPCHeader = false;
    /**
     * Generated from protobuf field <code>bool noSSEHeader = 7;</code>
     */
    protected $noSSEHeader = false;
    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig scMaxEachPostBytes = 8;</code>
     */
    protected $scMaxEachPostBytes = null;
    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig scMinPostsIntervalMs = 9;</code>
     */
    protected $scMinPostsIntervalMs = null;
    /**
     * Generated from protobuf field <code>int64 scMaxBufferedPosts = 10;</code>
     */
    protected $scMaxBufferedPosts = 0;
    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig scStreamUpServerSecs = 11;</code>
     */
    protected $scStreamUpServerSecs = null;
    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.XmuxConfig xmux = 12;</code>
     */
    protected $xmux = null;
    /**
     * Generated from protobuf field <code>.xray.transport.internet.StreamConfig downloadSettings = 13;</code>
     */
    protected $downloadSettings = null;
    /**
     * Generated from protobuf field <code>bool xPaddingObfsMode = 14;</code>
     */
    protected $xPaddingObfsMode = false;
    /**
     * Generated from protobuf field <code>string xPaddingKey = 15;</code>
     */
    protected $xPaddingKey = '';
    /**
     * Generated from protobuf field <code>string xPaddingHeader = 16;</code>
     */
    protected $xPaddingHeader = '';
    /**
     * Generated from protobuf field <code>string xPaddingPlacement = 17;</code>
     */
    protected $xPaddingPlacement = '';
    /**
     * Generated from protobuf field <code>string xPaddingMethod = 18;</code>
     */
    protected $xPaddingMethod = '';
    /**
     * Generated from protobuf field <code>string uplinkHTTPMethod = 19;</code>
     */
    protected $uplinkHTTPMethod = '';
    /**
     * Generated from protobuf field <code>string sessionPlacement = 20;</code>
     */
    protected $sessionPlacement = '';
    /**
     * Generated from protobuf field <code>string sessionKey = 21;</code>
     */
    protected $sessionKey = '';
    /**
     * Generated from protobuf field <code>string seqPlacement = 22;</code>
     */
    protected $seqPlacement = '';
    /**
     * Generated from protobuf field <code>string seqKey = 23;</code>
     */
    protected $seqKey = '';
    /**
     * Generated from protobuf field <code>string uplinkDataPlacement = 24;</code>
     */
    protected $uplinkDataPlacement = '';
    /**
     * Generated from protobuf field <code>string uplinkDataKey = 25;</code>
     */
    protected $uplinkDataKey = '';
    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig uplinkChunkSize = 26;</code>
     */
    protected $uplinkChunkSize = null;
    /**
     * Generated from protobuf field <code>int32 serverMaxHeaderBytes = 27;</code>
     */
    protected $serverMaxHeaderBytes = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $host
     *     @type string $path
     *     @type string $mode
     *     @type array|\Google\Protobuf\Internal\MapField $headers
     *     @type \Xray\Transport\Internet\Splithttp\RangeConfig $xPaddingBytes
     *     @type bool $noGRPCHeader
     *     @type bool $noSSEHeader
     *     @type \Xray\Transport\Internet\Splithttp\RangeConfig $scMaxEachPostBytes
     *     @type \Xray\Transport\Internet\Splithttp\RangeConfig $scMinPostsIntervalMs
     *     @type int|string $scMaxBufferedPosts
     *     @type \Xray\Transport\Internet\Splithttp\RangeConfig $scStreamUpServerSecs
     *     @type \Xray\Transport\Internet\Splithttp\XmuxConfig $xmux
     *     @type \Xray\Transport\Internet\StreamConfig $downloadSettings
     *     @type bool $xPaddingObfsMode
     *     @type string $xPaddingKey
     *     @type string $xPaddingHeader
     *     @type string $xPaddingPlacement
     *     @type string $xPaddingMethod
     *     @type string $uplinkHTTPMethod
     *     @type string $sessionPlacement
     *     @type string $sessionKey
     *     @type string $seqPlacement
     *     @type string $seqKey
     *     @type string $uplinkDataPlacement
     *     @type string $uplinkDataKey
     *     @type \Xray\Transport\Internet\Splithttp\RangeConfig $uplinkChunkSize
     *     @type int $serverMaxHeaderBytes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Splithttp\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string host = 1;</code>
     * @return string
     */
    public function getHost()
    {
        return $this->host;
    }

    /**
     * Generated from protobuf field <code>string host = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->host = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string path = 2;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>string path = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mode = 3;</code>
     * @return string
     */
    public function getMode()
    {
        return $this->mode;
    }

    /**
     * Generated from protobuf field <code>string mode = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMode($var)
    {
        GPBUtil::checkString($var, True);
        $this->mode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> headers = 4;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    /**
     * Generated from protobuf field <code>map<string, string> headers = 4;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setHeaders($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->headers = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig xPaddingBytes = 5;</code>
     * @return \Xray\Transport\Internet\Splithttp\RangeConfig|null
     */
    public function getXPaddingBytes()
    {
        return $this->xPaddingBytes;
    }

    public function hasXPaddingBytes()
    {
        return isset($this->xPaddingBytes);
    }

    public function clearXPaddingBytes()
    {
        unset($this->xPaddingBytes);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig xPaddingBytes = 5;</code>
     * @param \Xray\Transport\Internet\Splithttp\RangeConfig $var
     * @return $this
     */
    public function setXPaddingBytes($var)
    {
        GPBUtil::checkMessage($var, \Xray\Transport\Internet\Splithttp\RangeConfig::class);
        $this->xPaddingBytes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool noGRPCHeader = 6;</code>
     * @return bool
     */
    public function getNoGRPCHeader()
    {
        return $this->noGRPCHeader;
    }

    /**
     * Generated from protobuf field <code>bool noGRPCHeader = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setNoGRPCHeader($var)
    {
        GPBUtil::checkBool($var);
        $this->noGRPCHeader = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool noSSEHeader = 7;</code>
     * @return bool
     */
    public function getNoSSEHeader()
    {
        return $this->noSSEHeader;
    }

    /**
     * Generated from protobuf field <code>bool noSSEHeader = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setNoSSEHeader($var)
    {
        GPBUtil::checkBool($var);
        $this->noSSEHeader = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig scMaxEachPostBytes = 8;</code>
     * @return \Xray\Transport\Internet\Splithttp\RangeConfig|null
     */
    public function getScMaxEachPostBytes()
    {
        return $this->scMaxEachPostBytes;
    }

    public function hasScMaxEachPostBytes()
    {
        return isset($this->scMaxEachPostBytes);
    }

    public function clearScMaxEachPostBytes()
    {
        unset($this->scMaxEachPostBytes);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig scMaxEachPostBytes = 8;</code>
     * @param \Xray\Transport\Internet\Splithttp\RangeConfig $var
     * @return $this
     */
    public function setScMaxEachPostBytes($var)
    {
        GPBUtil::checkMessage($var, \Xray\Transport\Internet\Splithttp\RangeConfig::class);
        $this->scMaxEachPostBytes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig scMinPostsIntervalMs = 9;</code>
     * @return \Xray\Transport\Internet\Splithttp\RangeConfig|null
     */
    public function getScMinPostsIntervalMs()
    {
        return $this->scMinPostsIntervalMs;
    }

    public function hasScMinPostsIntervalMs()
    {
        return isset($this->scMinPostsIntervalMs);
    }

    public function clearScMinPostsIntervalMs()
    {
        unset($this->scMinPostsIntervalMs);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig scMinPostsIntervalMs = 9;</code>
     * @param \Xray\Transport\Internet\Splithttp\RangeConfig $var
     * @return $this
     */
    public function setScMinPostsIntervalMs($var)
    {
        GPBUtil::checkMessage($var, \Xray\Transport\Internet\Splithttp\RangeConfig::class);
        $this->scMinPostsIntervalMs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 scMaxBufferedPosts = 10;</code>
     * @return int|string
     */
    public function getScMaxBufferedPosts()
    {
        return $this->scMaxBufferedPosts;
    }

    /**
     * Generated from protobuf field <code>int64 scMaxBufferedPosts = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setScMaxBufferedPosts($var)
    {
        GPBUtil::checkInt64($var);
        $this->scMaxBufferedPosts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig scStreamUpServerSecs = 11;</code>
     * @return \Xray\Transport\Internet\Splithttp\RangeConfig|null
     */
    public function getScStreamUpServerSecs()
    {
        return $this->scStreamUpServerSecs;
    }

    public function hasScStreamUpServerSecs()
    {
        return isset($this->scStreamUpServerSecs);
    }

    public function clearScStreamUpServerSecs()
    {
        unset($this->scStreamUpServerSecs);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig scStreamUpServerSecs = 11;</code>
     * @param \Xray\Transport\Internet\Splithttp\RangeConfig $var
     * @return $this
     */
    public function setScStreamUpServerSecs($var)
    {
        GPBUtil::checkMessage($var, \Xray\Transport\Internet\Splithttp\RangeConfig::class);
        $this->scStreamUpServerSecs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.XmuxConfig xmux = 12;</code>
     * @return \Xray\Transport\Internet\Splithttp\XmuxConfig|null
     */
    public function getXmux()
    {
        return $this->xmux;
    }

    public function hasXmux()
    {
        return isset($this->xmux);
    }

    public function clearXmux()
    {
        unset($this->xmux);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.XmuxConfig xmux = 12;</code>
     * @param \Xray\Transport\Internet\Splithttp\XmuxConfig $var
     * @return $this
     */
    public function setXmux($var)
    {
        GPBUtil::checkMessage($var, \Xray\Transport\Internet\Splithttp\XmuxConfig::class);
        $this->xmux = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.StreamConfig downloadSettings = 13;</code>
     * @return \Xray\Transport\Internet\StreamConfig|null
     */
    public function getDownloadSettings()
    {
        return $this->downloadSettings;
    }

    public function hasDownloadSettings()
    {
        return isset($this->downloadSettings);
    }

    public function clearDownloadSettings()
    {
        unset($this->downloadSettings);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.StreamConfig downloadSettings = 13;</code>
     * @param \Xray\Transport\Internet\StreamConfig $var
     * @return $this
     */
    public function setDownloadSettings($var)
    {
        GPBUtil::checkMessage($var, \Xray\Transport\Internet\StreamConfig::class);
        $this->downloadSettings = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool xPaddingObfsMode = 14;</code>
     * @return bool
     */
    public function getXPaddingObfsMode()
    {
        return $this->xPaddingObfsMode;
    }

    /**
     * Generated from protobuf field <code>bool xPaddingObfsMode = 14;</code>
     * @param bool $var
     * @return $this
     */
    public function setXPaddingObfsMode($var)
    {
        GPBUtil::checkBool($var);
        $this->xPaddingObfsMode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string xPaddingKey = 15;</code>
     * @return string
     */
    public function getXPaddingKey()
    {
        return $this->xPaddingKey;
    }

    /**
     * Generated from protobuf field <code>string xPaddingKey = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setXPaddingKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->xPaddingKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string xPaddingHeader = 16;</code>
     * @return string
     */
    public function getXPaddingHeader()
    {
        return $this->xPaddingHeader;
    }

    /**
     * Generated from protobuf field <code>string xPaddingHeader = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setXPaddingHeader($var)
    {
        GPBUtil::checkString($var, True);
        $this->xPaddingHeader = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string xPaddingPlacement = 17;</code>
     * @return string
     */
    public function getXPaddingPlacement()
    {
        return $this->xPaddingPlacement;
    }

    /**
     * Generated from protobuf field <code>string xPaddingPlacement = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setXPaddingPlacement($var)
    {
        GPBUtil::checkString($var, True);
        $this->xPaddingPlacement = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string xPaddingMethod = 18;</code>
     * @return string
     */
    public function getXPaddingMethod()
    {
        return $this->xPaddingMethod;
    }

    /**
     * Generated from protobuf field <code>string xPaddingMethod = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setXPaddingMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->xPaddingMethod = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string uplinkHTTPMethod = 19;</code>
     * @return string
     */
    public function getUplinkHTTPMethod()
    {
        return $this->uplinkHTTPMethod;
    }

    /**
     * Generated from protobuf field <code>string uplinkHTTPMethod = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setUplinkHTTPMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->uplinkHTTPMethod = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sessionPlacement = 20;</code>
     * @return string
     */
    public function getSessionPlacement()
    {
        return $this->sessionPlacement;
    }

    /**
     * Generated from protobuf field <code>string sessionPlacement = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionPlacement($var)
    {
        GPBUtil::checkString($var, True);
        $this->sessionPlacement = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sessionKey = 21;</code>
     * @return string
     */
    public function getSessionKey()
    {
        return $this->sessionKey;
    }

    /**
     * Generated from protobuf field <code>string sessionKey = 21;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->sessionKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string seqPlacement = 22;</code>
     * @return string
     */
    public function getSeqPlacement()
    {
        return $this->seqPlacement;
    }

    /**
     * Generated from protobuf field <code>string seqPlacement = 22;</code>
     * @param string $var
     * @return $this
     */
    public function setSeqPlacement($var)
    {
        GPBUtil::checkString($var, True);
        $this->seqPlacement = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string seqKey = 23;</code>
     * @return string
     */
    public function getSeqKey()
    {
        return $this->seqKey;
    }

    /**
     * Generated from protobuf field <code>string seqKey = 23;</code>
     * @param string $var
     * @return $this
     */
    public function setSeqKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->seqKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string uplinkDataPlacement = 24;</code>
     * @return string
     */
    public function getUplinkDataPlacement()
    {
        return $this->uplinkDataPlacement;
    }

    /**
     * Generated from protobuf field <code>string uplinkDataPlacement = 24;</code>
     * @param string $var
     * @return $this
     */
    public function setUplinkDataPlacement($var)
    {
        GPBUtil::checkString($var, True);
        $this->uplinkDataPlacement = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string uplinkDataKey = 25;</code>
     * @return string
     */
    public function getUplinkDataKey()
    {
        return $this->uplinkDataKey;
    }

    /**
     * Generated from protobuf field <code>string uplinkDataKey = 25;</code>
     * @param string $var
     * @return $this
     */
    public function setUplinkDataKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->uplinkDataKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig uplinkChunkSize = 26;</code>
     * @return \Xray\Transport\Internet\Splithttp\RangeConfig|null
     */
    public function getUplinkChunkSize()
    {
        return $this->uplinkChunkSize;
    }

    public function hasUplinkChunkSize()
    {
        return isset($this->uplinkChunkSize);
    }

    public function clearUplinkChunkSize()
    {
        unset($this->uplinkChunkSize);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig uplinkChunkSize = 26;</code>
     * @param \Xray\Transport\Internet\Splithttp\RangeConfig $var
     * @return $this
     */
    public function setUplinkChunkSize($var)
    {
        GPBUtil::checkMessage($var, \Xray\Transport\Internet\Splithttp\RangeConfig::class);
        $this->uplinkChunkSize = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 serverMaxHeaderBytes = 27;</code>
     * @return int
     */
    public function getServerMaxHeaderBytes()
    {
        return $this->serverMaxHeaderBytes;
    }

    /**
     * Generated from protobuf field <code>int32 serverMaxHeaderBytes = 27;</code>
     * @param int $var
     * @return $this
     */
    public function setServerMaxHeaderBytes($var)
    {
        GPBUtil::checkInt32($var);
        $this->serverMaxHeaderBytes = $var;

        return $this;
    }

}

