<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/splithttp/config.proto

namespace Xray\Transport\Internet\Splithttp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.splithttp.XmuxConfig</code>
 */
class XmuxConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig maxConcurrency = 1;</code>
     */
    protected $maxConcurrency = null;
    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig maxConnections = 2;</code>
     */
    protected $maxConnections = null;
    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig cMaxReuseTimes = 3;</code>
     */
    protected $cMaxReuseTimes = null;
    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig hMaxRequestTimes = 4;</code>
     */
    protected $hMaxRequestTimes = null;
    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig hMaxReusableSecs = 5;</code>
     */
    protected $hMaxReusableSecs = null;
    /**
     * Generated from protobuf field <code>int64 hKeepAlivePeriod = 6;</code>
     */
    protected $hKeepAlivePeriod = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Xray\Transport\Internet\Splithttp\RangeConfig $maxConcurrency
     *     @type \Xray\Transport\Internet\Splithttp\RangeConfig $maxConnections
     *     @type \Xray\Transport\Internet\Splithttp\RangeConfig $cMaxReuseTimes
     *     @type \Xray\Transport\Internet\Splithttp\RangeConfig $hMaxRequestTimes
     *     @type \Xray\Transport\Internet\Splithttp\RangeConfig $hMaxReusableSecs
     *     @type int|string $hKeepAlivePeriod
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Splithttp\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig maxConcurrency = 1;</code>
     * @return \Xray\Transport\Internet\Splithttp\RangeConfig|null
     */
    public function getMaxConcurrency()
    {
        return $this->maxConcurrency;
    }

    public function hasMaxConcurrency()
    {
        return isset($this->maxConcurrency);
    }

    public function clearMaxConcurrency()
    {
        unset($this->maxConcurrency);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig maxConcurrency = 1;</code>
     * @param \Xray\Transport\Internet\Splithttp\RangeConfig $var
     * @return $this
     */
    public function setMaxConcurrency($var)
    {
        GPBUtil::checkMessage($var, \Xray\Transport\Internet\Splithttp\RangeConfig::class);
        $this->maxConcurrency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig maxConnections = 2;</code>
     * @return \Xray\Transport\Internet\Splithttp\RangeConfig|null
     */
    public function getMaxConnections()
    {
        return $this->maxConnections;
    }

    public function hasMaxConnections()
    {
        return isset($this->maxConnections);
    }

    public function clearMaxConnections()
    {
        unset($this->maxConnections);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig maxConnections = 2;</code>
     * @param \Xray\Transport\Internet\Splithttp\RangeConfig $var
     * @return $this
     */
    public function setMaxConnections($var)
    {
        GPBUtil::checkMessage($var, \Xray\Transport\Internet\Splithttp\RangeConfig::class);
        $this->maxConnections = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig cMaxReuseTimes = 3;</code>
     * @return \Xray\Transport\Internet\Splithttp\RangeConfig|null
     */
    public function getCMaxReuseTimes()
    {
        return $this->cMaxReuseTimes;
    }

    public function hasCMaxReuseTimes()
    {
        return isset($this->cMaxReuseTimes);
    }

    public function clearCMaxReuseTimes()
    {
        unset($this->cMaxReuseTimes);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig cMaxReuseTimes = 3;</code>
     * @param \Xray\Transport\Internet\Splithttp\RangeConfig $var
     * @return $this
     */
    public function setCMaxReuseTimes($var)
    {
        GPBUtil::checkMessage($var, \Xray\Transport\Internet\Splithttp\RangeConfig::class);
        $this->cMaxReuseTimes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig hMaxRequestTimes = 4;</code>
     * @return \Xray\Transport\Internet\Splithttp\RangeConfig|null
     */
    public function getHMaxRequestTimes()
    {
        return $this->hMaxRequestTimes;
    }

    public function hasHMaxRequestTimes()
    {
        return isset($this->hMaxRequestTimes);
    }

    public function clearHMaxRequestTimes()
    {
        unset($this->hMaxRequestTimes);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig hMaxRequestTimes = 4;</code>
     * @param \Xray\Transport\Internet\Splithttp\RangeConfig $var
     * @return $this
     */
    public function setHMaxRequestTimes($var)
    {
        GPBUtil::checkMessage($var, \Xray\Transport\Internet\Splithttp\RangeConfig::class);
        $this->hMaxRequestTimes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig hMaxReusableSecs = 5;</code>
     * @return \Xray\Transport\Internet\Splithttp\RangeConfig|null
     */
    public function getHMaxReusableSecs()
    {
        return $this->hMaxReusableSecs;
    }

    public function hasHMaxReusableSecs()
    {
        return isset($this->hMaxReusableSecs);
    }

    public function clearHMaxReusableSecs()
    {
        unset($this->hMaxReusableSecs);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.splithttp.RangeConfig hMaxReusableSecs = 5;</code>
     * @param \Xray\Transport\Internet\Splithttp\RangeConfig $var
     * @return $this
     */
    public function setHMaxReusableSecs($var)
    {
        GPBUtil::checkMessage($var, \Xray\Transport\Internet\Splithttp\RangeConfig::class);
        $this->hMaxReusableSecs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 hKeepAlivePeriod = 6;</code>
     * @return int|string
     */
    public function getHKeepAlivePeriod()
    {
        return $this->hKeepAlivePeriod;
    }

    /**
     * Generated from protobuf field <code>int64 hKeepAlivePeriod = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setHKeepAlivePeriod($var)
    {
        GPBUtil::checkInt64($var);
        $this->hKeepAlivePeriod = $var;

        return $this;
    }

}

