<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/dns/config.proto

namespace Xray\Proxy\Dns;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.proxy.dns.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 user_level = 1;</code>
     */
    protected $user_level = 0;
    /**
     * Generated from protobuf field <code>repeated .xray.proxy.dns.DNSRuleConfig rule = 2;</code>
     */
    private $rule;
    /**
     * Generated from protobuf field <code>.xray.common.net.Endpoint rewrite_server = 3;</code>
     */
    protected $rewrite_server = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $user_level
     *     @type array<\Xray\Proxy\Dns\DNSRuleConfig>|\Google\Protobuf\Internal\RepeatedField $rule
     *     @type \Xray\Common\Net\Endpoint $rewrite_server
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Dns\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 user_level = 1;</code>
     * @return int
     */
    public function getUserLevel()
    {
        return $this->user_level;
    }

    /**
     * Generated from protobuf field <code>uint32 user_level = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUserLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->user_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.proxy.dns.DNSRuleConfig rule = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRule()
    {
        return $this->rule;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.proxy.dns.DNSRuleConfig rule = 2;</code>
     * @param array<\Xray\Proxy\Dns\DNSRuleConfig>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRule($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Proxy\Dns\DNSRuleConfig::class);
        $this->rule = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.common.net.Endpoint rewrite_server = 3;</code>
     * @return \Xray\Common\Net\Endpoint|null
     */
    public function getRewriteServer()
    {
        return $this->rewrite_server;
    }

    public function hasRewriteServer()
    {
        return isset($this->rewrite_server);
    }

    public function clearRewriteServer()
    {
        unset($this->rewrite_server);
    }

    /**
     * Generated from protobuf field <code>.xray.common.net.Endpoint rewrite_server = 3;</code>
     * @param \Xray\Common\Net\Endpoint $var
     * @return $this
     */
    public function setRewriteServer($var)
    {
        GPBUtil::checkMessage($var, \Xray\Common\Net\Endpoint::class);
        $this->rewrite_server = $var;

        return $this;
    }

}

