<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/dns/config.proto

namespace Xray\Proxy\Dns;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.proxy.dns.DNSRuleConfig</code>
 */
class DNSRuleConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.xray.proxy.dns.RuleAction action = 1;</code>
     */
    protected $action = 0;
    /**
     * Generated from protobuf field <code>repeated int32 qtype = 2;</code>
     */
    private $qtype;
    /**
     * Generated from protobuf field <code>repeated .xray.common.geodata.DomainRule domain = 3;</code>
     */
    private $domain;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $action
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $qtype
     *     @type array<\Xray\Common\Geodata\DomainRule>|\Google\Protobuf\Internal\RepeatedField $domain
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Dns\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xray.proxy.dns.RuleAction action = 1;</code>
     * @return int
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Generated from protobuf field <code>.xray.proxy.dns.RuleAction action = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkEnum($var, \Xray\Proxy\Dns\RuleAction::class);
        $this->action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 qtype = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getQtype()
    {
        return $this->qtype;
    }

    /**
     * Generated from protobuf field <code>repeated int32 qtype = 2;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setQtype($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->qtype = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.geodata.DomainRule domain = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDomain()
    {
        return $this->domain;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.geodata.DomainRule domain = 3;</code>
     * @param array<\Xray\Common\Geodata\DomainRule>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDomain($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Common\Geodata\DomainRule::class);
        $this->domain = $arr;

        return $this;
    }

}

