<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/dns/config.proto

namespace Xray\Proxy\Dns;

use UnexpectedValueException;

/**
 * Protobuf type <code>xray.proxy.dns.RuleAction</code>
 */
class RuleAction
{
    /**
     * Generated from protobuf enum <code>Direct = 0;</code>
     */
    const Direct = 0;
    /**
     * Generated from protobuf enum <code>Drop = 1;</code>
     */
    const Drop = 1;
    /**
     * Generated from protobuf enum <code>Reject = 2;</code>
     */
    const Reject = 2;
    /**
     * Generated from protobuf enum <code>Hijack = 3;</code>
     */
    const Hijack = 3;

    private static $valueToName = [
        self::Direct => 'Direct',
        self::Drop => 'Drop',
        self::Reject => 'Reject',
        self::Hijack => 'Hijack',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

