<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/router/config.proto

namespace Xray\App\Router;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.app.router.RoutingRule</code>
 */
class RoutingRule extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string rule_tag = 19;</code>
     */
    protected $rule_tag = '';
    /**
     * List of domains for target domain matching.
     *
     * Generated from protobuf field <code>repeated .xray.common.geodata.DomainRule domain = 2;</code>
     */
    private $domain;
    /**
     * List of IPs for target IP address matching.
     *
     * Generated from protobuf field <code>repeated .xray.common.geodata.IPRule ip = 10;</code>
     */
    private $ip;
    /**
     * List of ports for target port matching.
     *
     * Generated from protobuf field <code>.xray.common.net.PortList port_list = 14;</code>
     */
    protected $port_list = null;
    /**
     * List of networks for matching.
     *
     * Generated from protobuf field <code>repeated .xray.common.net.Network networks = 13;</code>
     */
    private $networks;
    /**
     * List of IPs for source IP address matching.
     *
     * Generated from protobuf field <code>repeated .xray.common.geodata.IPRule source_ip = 11;</code>
     */
    private $source_ip;
    /**
     * List of ports for source port matching.
     *
     * Generated from protobuf field <code>.xray.common.net.PortList source_port_list = 16;</code>
     */
    protected $source_port_list = null;
    /**
     * Generated from protobuf field <code>repeated string user_email = 7;</code>
     */
    private $user_email;
    /**
     * Generated from protobuf field <code>repeated string inbound_tag = 8;</code>
     */
    private $inbound_tag;
    /**
     * Generated from protobuf field <code>repeated string protocol = 9;</code>
     */
    private $protocol;
    /**
     * Generated from protobuf field <code>map<string, string> attributes = 15;</code>
     */
    private $attributes;
    /**
     * List of IPs for local IP address matching.
     *
     * Generated from protobuf field <code>repeated .xray.common.geodata.IPRule local_ip = 17;</code>
     */
    private $local_ip;
    /**
     * List of ports for local port matching.
     *
     * Generated from protobuf field <code>.xray.common.net.PortList local_port_list = 18;</code>
     */
    protected $local_port_list = null;
    /**
     * Generated from protobuf field <code>.xray.common.net.PortList vless_route_list = 20;</code>
     */
    protected $vless_route_list = null;
    /**
     * Generated from protobuf field <code>repeated string process = 21;</code>
     */
    private $process;
    /**
     * Generated from protobuf field <code>.xray.app.router.WebhookConfig webhook = 22;</code>
     */
    protected $webhook = null;
    protected $target_tag;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tag
     *           Tag of outbound that this rule is pointing to.
     *     @type string $balancing_tag
     *           Tag of routing balancer.
     *     @type string $rule_tag
     *     @type array<\Xray\Common\Geodata\DomainRule>|\Google\Protobuf\Internal\RepeatedField $domain
     *           List of domains for target domain matching.
     *     @type array<\Xray\Common\Geodata\IPRule>|\Google\Protobuf\Internal\RepeatedField $ip
     *           List of IPs for target IP address matching.
     *     @type \Xray\Common\Net\PortList $port_list
     *           List of ports for target port matching.
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $networks
     *           List of networks for matching.
     *     @type array<\Xray\Common\Geodata\IPRule>|\Google\Protobuf\Internal\RepeatedField $source_ip
     *           List of IPs for source IP address matching.
     *     @type \Xray\Common\Net\PortList $source_port_list
     *           List of ports for source port matching.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $user_email
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $inbound_tag
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $protocol
     *     @type array|\Google\Protobuf\Internal\MapField $attributes
     *     @type array<\Xray\Common\Geodata\IPRule>|\Google\Protobuf\Internal\RepeatedField $local_ip
     *           List of IPs for local IP address matching.
     *     @type \Xray\Common\Net\PortList $local_port_list
     *           List of ports for local port matching.
     *     @type \Xray\Common\Net\PortList $vless_route_list
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $process
     *     @type \Xray\App\Router\WebhookConfig $webhook
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Router\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Tag of outbound that this rule is pointing to.
     *
     * Generated from protobuf field <code>string tag = 1;</code>
     * @return string
     */
    public function getTag()
    {
        return $this->readOneof(1);
    }

    public function hasTag()
    {
        return $this->hasOneof(1);
    }

    /**
     * Tag of outbound that this rule is pointing to.
     *
     * Generated from protobuf field <code>string tag = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Tag of routing balancer.
     *
     * Generated from protobuf field <code>string balancing_tag = 12;</code>
     * @return string
     */
    public function getBalancingTag()
    {
        return $this->readOneof(12);
    }

    public function hasBalancingTag()
    {
        return $this->hasOneof(12);
    }

    /**
     * Tag of routing balancer.
     *
     * Generated from protobuf field <code>string balancing_tag = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setBalancingTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(12, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rule_tag = 19;</code>
     * @return string
     */
    public function getRuleTag()
    {
        return $this->rule_tag;
    }

    /**
     * Generated from protobuf field <code>string rule_tag = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setRuleTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->rule_tag = $var;

        return $this;
    }

    /**
     * List of domains for target domain matching.
     *
     * Generated from protobuf field <code>repeated .xray.common.geodata.DomainRule domain = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDomain()
    {
        return $this->domain;
    }

    /**
     * List of domains for target domain matching.
     *
     * Generated from protobuf field <code>repeated .xray.common.geodata.DomainRule domain = 2;</code>
     * @param array<\Xray\Common\Geodata\DomainRule>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDomain($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Common\Geodata\DomainRule::class);
        $this->domain = $arr;

        return $this;
    }

    /**
     * List of IPs for target IP address matching.
     *
     * Generated from protobuf field <code>repeated .xray.common.geodata.IPRule ip = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     * List of IPs for target IP address matching.
     *
     * Generated from protobuf field <code>repeated .xray.common.geodata.IPRule ip = 10;</code>
     * @param array<\Xray\Common\Geodata\IPRule>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIp($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Common\Geodata\IPRule::class);
        $this->ip = $arr;

        return $this;
    }

    /**
     * List of ports for target port matching.
     *
     * Generated from protobuf field <code>.xray.common.net.PortList port_list = 14;</code>
     * @return \Xray\Common\Net\PortList|null
     */
    public function getPortList()
    {
        return $this->port_list;
    }

    public function hasPortList()
    {
        return isset($this->port_list);
    }

    public function clearPortList()
    {
        unset($this->port_list);
    }

    /**
     * List of ports for target port matching.
     *
     * Generated from protobuf field <code>.xray.common.net.PortList port_list = 14;</code>
     * @param \Xray\Common\Net\PortList $var
     * @return $this
     */
    public function setPortList($var)
    {
        GPBUtil::checkMessage($var, \Xray\Common\Net\PortList::class);
        $this->port_list = $var;

        return $this;
    }

    /**
     * List of networks for matching.
     *
     * Generated from protobuf field <code>repeated .xray.common.net.Network networks = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNetworks()
    {
        return $this->networks;
    }

    /**
     * List of networks for matching.
     *
     * Generated from protobuf field <code>repeated .xray.common.net.Network networks = 13;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNetworks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Xray\Common\Net\Network::class);
        $this->networks = $arr;

        return $this;
    }

    /**
     * List of IPs for source IP address matching.
     *
     * Generated from protobuf field <code>repeated .xray.common.geodata.IPRule source_ip = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSourceIp()
    {
        return $this->source_ip;
    }

    /**
     * List of IPs for source IP address matching.
     *
     * Generated from protobuf field <code>repeated .xray.common.geodata.IPRule source_ip = 11;</code>
     * @param array<\Xray\Common\Geodata\IPRule>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSourceIp($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Common\Geodata\IPRule::class);
        $this->source_ip = $arr;

        return $this;
    }

    /**
     * List of ports for source port matching.
     *
     * Generated from protobuf field <code>.xray.common.net.PortList source_port_list = 16;</code>
     * @return \Xray\Common\Net\PortList|null
     */
    public function getSourcePortList()
    {
        return $this->source_port_list;
    }

    public function hasSourcePortList()
    {
        return isset($this->source_port_list);
    }

    public function clearSourcePortList()
    {
        unset($this->source_port_list);
    }

    /**
     * List of ports for source port matching.
     *
     * Generated from protobuf field <code>.xray.common.net.PortList source_port_list = 16;</code>
     * @param \Xray\Common\Net\PortList $var
     * @return $this
     */
    public function setSourcePortList($var)
    {
        GPBUtil::checkMessage($var, \Xray\Common\Net\PortList::class);
        $this->source_port_list = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string user_email = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserEmail()
    {
        return $this->user_email;
    }

    /**
     * Generated from protobuf field <code>repeated string user_email = 7;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserEmail($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->user_email = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string inbound_tag = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInboundTag()
    {
        return $this->inbound_tag;
    }

    /**
     * Generated from protobuf field <code>repeated string inbound_tag = 8;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInboundTag($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->inbound_tag = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string protocol = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProtocol()
    {
        return $this->protocol;
    }

    /**
     * Generated from protobuf field <code>repeated string protocol = 9;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProtocol($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->protocol = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> attributes = 15;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    /**
     * Generated from protobuf field <code>map<string, string> attributes = 15;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setAttributes($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->attributes = $arr;

        return $this;
    }

    /**
     * List of IPs for local IP address matching.
     *
     * Generated from protobuf field <code>repeated .xray.common.geodata.IPRule local_ip = 17;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLocalIp()
    {
        return $this->local_ip;
    }

    /**
     * List of IPs for local IP address matching.
     *
     * Generated from protobuf field <code>repeated .xray.common.geodata.IPRule local_ip = 17;</code>
     * @param array<\Xray\Common\Geodata\IPRule>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLocalIp($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Common\Geodata\IPRule::class);
        $this->local_ip = $arr;

        return $this;
    }

    /**
     * List of ports for local port matching.
     *
     * Generated from protobuf field <code>.xray.common.net.PortList local_port_list = 18;</code>
     * @return \Xray\Common\Net\PortList|null
     */
    public function getLocalPortList()
    {
        return $this->local_port_list;
    }

    public function hasLocalPortList()
    {
        return isset($this->local_port_list);
    }

    public function clearLocalPortList()
    {
        unset($this->local_port_list);
    }

    /**
     * List of ports for local port matching.
     *
     * Generated from protobuf field <code>.xray.common.net.PortList local_port_list = 18;</code>
     * @param \Xray\Common\Net\PortList $var
     * @return $this
     */
    public function setLocalPortList($var)
    {
        GPBUtil::checkMessage($var, \Xray\Common\Net\PortList::class);
        $this->local_port_list = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.common.net.PortList vless_route_list = 20;</code>
     * @return \Xray\Common\Net\PortList|null
     */
    public function getVlessRouteList()
    {
        return $this->vless_route_list;
    }

    public function hasVlessRouteList()
    {
        return isset($this->vless_route_list);
    }

    public function clearVlessRouteList()
    {
        unset($this->vless_route_list);
    }

    /**
     * Generated from protobuf field <code>.xray.common.net.PortList vless_route_list = 20;</code>
     * @param \Xray\Common\Net\PortList $var
     * @return $this
     */
    public function setVlessRouteList($var)
    {
        GPBUtil::checkMessage($var, \Xray\Common\Net\PortList::class);
        $this->vless_route_list = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string process = 21;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProcess()
    {
        return $this->process;
    }

    /**
     * Generated from protobuf field <code>repeated string process = 21;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProcess($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->process = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.app.router.WebhookConfig webhook = 22;</code>
     * @return \Xray\App\Router\WebhookConfig|null
     */
    public function getWebhook()
    {
        return $this->webhook;
    }

    public function hasWebhook()
    {
        return isset($this->webhook);
    }

    public function clearWebhook()
    {
        unset($this->webhook);
    }

    /**
     * Generated from protobuf field <code>.xray.app.router.WebhookConfig webhook = 22;</code>
     * @param \Xray\App\Router\WebhookConfig $var
     * @return $this
     */
    public function setWebhook($var)
    {
        GPBUtil::checkMessage($var, \Xray\App\Router\WebhookConfig::class);
        $this->webhook = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getTargetTag()
    {
        return $this->whichOneof("target_tag");
    }

}

