<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/hysteria/account/config.proto

namespace GPBMetadata\Proxy\Hysteria\Account;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ø
#proxy/hysteria/account/config.protoxray.proxy.hysteria.account"
Account
auth (	Bs
com.xray.proxy.hysteria.accountPZ0github.com/xtls/xray-core/proxy/hysteria/accountªXray.Proxy.Hysteria.Accountbproto3'
        , true);

        static::$is_initialized = true;
    }
}

