<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/finalmask/xdns/config.proto

namespace GPBMetadata\Transport\Internet\Finalmask\Xdns;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¥
.transport/internet/finalmask/xdns/config.proto&xray.transport.internet.finalmask.xdns",
Config
domains (	
	resolvers (	B”
*com.xray.transport.internet.finalmask.xdnsPZ;github.com/xtls/xray-core/transport/internet/finalmask/xdnsª&Xray.Transport.Internet.Finalmask.Xdnsbproto3'
        , true);

        static::$is_initialized = true;
    }
}

