<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/finalmask/header/wechat/config.proto

namespace Xray\Transport\Internet\Finalmask\Header\Wechat;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.finalmask.header.wechat.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Finalmask\Header\Wechat\Config::initOnce();
        parent::__construct($data);
    }

}

