<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/hysteria/config.proto

namespace Xray\Transport\Internet\Hysteria;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.hysteria.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 version = 1;</code>
     */
    protected $version = 0;
    /**
     * Generated from protobuf field <code>string auth = 2;</code>
     */
    protected $auth = '';
    /**
     * Generated from protobuf field <code>int64 udp_idle_timeout = 3;</code>
     */
    protected $udp_idle_timeout = 0;
    /**
     * Generated from protobuf field <code>string masq_type = 4;</code>
     */
    protected $masq_type = '';
    /**
     * Generated from protobuf field <code>string masq_file = 5;</code>
     */
    protected $masq_file = '';
    /**
     * Generated from protobuf field <code>string masq_url = 6;</code>
     */
    protected $masq_url = '';
    /**
     * Generated from protobuf field <code>bool masq_url_rewrite_host = 7;</code>
     */
    protected $masq_url_rewrite_host = false;
    /**
     * Generated from protobuf field <code>bool masq_url_insecure = 8;</code>
     */
    protected $masq_url_insecure = false;
    /**
     * Generated from protobuf field <code>string masq_string = 9;</code>
     */
    protected $masq_string = '';
    /**
     * Generated from protobuf field <code>map<string, string> masq_string_headers = 10;</code>
     */
    private $masq_string_headers;
    /**
     * Generated from protobuf field <code>int32 masq_string_status_code = 11;</code>
     */
    protected $masq_string_status_code = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $version
     *     @type string $auth
     *     @type int|string $udp_idle_timeout
     *     @type string $masq_type
     *     @type string $masq_file
     *     @type string $masq_url
     *     @type bool $masq_url_rewrite_host
     *     @type bool $masq_url_insecure
     *     @type string $masq_string
     *     @type array|\Google\Protobuf\Internal\MapField $masq_string_headers
     *     @type int $masq_string_status_code
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Hysteria\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 version = 1;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>int32 version = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string auth = 2;</code>
     * @return string
     */
    public function getAuth()
    {
        return $this->auth;
    }

    /**
     * Generated from protobuf field <code>string auth = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAuth($var)
    {
        GPBUtil::checkString($var, True);
        $this->auth = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 udp_idle_timeout = 3;</code>
     * @return int|string
     */
    public function getUdpIdleTimeout()
    {
        return $this->udp_idle_timeout;
    }

    /**
     * Generated from protobuf field <code>int64 udp_idle_timeout = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUdpIdleTimeout($var)
    {
        GPBUtil::checkInt64($var);
        $this->udp_idle_timeout = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string masq_type = 4;</code>
     * @return string
     */
    public function getMasqType()
    {
        return $this->masq_type;
    }

    /**
     * Generated from protobuf field <code>string masq_type = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMasqType($var)
    {
        GPBUtil::checkString($var, True);
        $this->masq_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string masq_file = 5;</code>
     * @return string
     */
    public function getMasqFile()
    {
        return $this->masq_file;
    }

    /**
     * Generated from protobuf field <code>string masq_file = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMasqFile($var)
    {
        GPBUtil::checkString($var, True);
        $this->masq_file = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string masq_url = 6;</code>
     * @return string
     */
    public function getMasqUrl()
    {
        return $this->masq_url;
    }

    /**
     * Generated from protobuf field <code>string masq_url = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMasqUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->masq_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool masq_url_rewrite_host = 7;</code>
     * @return bool
     */
    public function getMasqUrlRewriteHost()
    {
        return $this->masq_url_rewrite_host;
    }

    /**
     * Generated from protobuf field <code>bool masq_url_rewrite_host = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setMasqUrlRewriteHost($var)
    {
        GPBUtil::checkBool($var);
        $this->masq_url_rewrite_host = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool masq_url_insecure = 8;</code>
     * @return bool
     */
    public function getMasqUrlInsecure()
    {
        return $this->masq_url_insecure;
    }

    /**
     * Generated from protobuf field <code>bool masq_url_insecure = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setMasqUrlInsecure($var)
    {
        GPBUtil::checkBool($var);
        $this->masq_url_insecure = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string masq_string = 9;</code>
     * @return string
     */
    public function getMasqString()
    {
        return $this->masq_string;
    }

    /**
     * Generated from protobuf field <code>string masq_string = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setMasqString($var)
    {
        GPBUtil::checkString($var, True);
        $this->masq_string = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> masq_string_headers = 10;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMasqStringHeaders()
    {
        return $this->masq_string_headers;
    }

    /**
     * Generated from protobuf field <code>map<string, string> masq_string_headers = 10;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMasqStringHeaders($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->masq_string_headers = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 masq_string_status_code = 11;</code>
     * @return int
     */
    public function getMasqStringStatusCode()
    {
        return $this->masq_string_status_code;
    }

    /**
     * Generated from protobuf field <code>int32 masq_string_status_code = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setMasqStringStatusCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->masq_string_status_code = $var;

        return $this;
    }

}

