<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/dns/config.proto

namespace Xray\App\Dns\Config;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.app.dns.Config.HostMapping</code>
 */
class HostMapping extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.xray.common.geodata.DomainRule domain = 2;</code>
     */
    protected $domain = null;
    /**
     * Generated from protobuf field <code>repeated bytes ip = 3;</code>
     */
    private $ip;
    /**
     * ProxiedDomain indicates the mapped domain has the same IP address on this
     * domain. Xray will use this domain for IP queries.
     *
     * Generated from protobuf field <code>string proxied_domain = 4;</code>
     */
    protected $proxied_domain = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Xray\Common\Geodata\DomainRule $domain
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $ip
     *     @type string $proxied_domain
     *           ProxiedDomain indicates the mapped domain has the same IP address on this
     *           domain. Xray will use this domain for IP queries.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Dns\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xray.common.geodata.DomainRule domain = 2;</code>
     * @return \Xray\Common\Geodata\DomainRule|null
     */
    public function getDomain()
    {
        return $this->domain;
    }

    public function hasDomain()
    {
        return isset($this->domain);
    }

    public function clearDomain()
    {
        unset($this->domain);
    }

    /**
     * Generated from protobuf field <code>.xray.common.geodata.DomainRule domain = 2;</code>
     * @param \Xray\Common\Geodata\DomainRule $var
     * @return $this
     */
    public function setDomain($var)
    {
        GPBUtil::checkMessage($var, \Xray\Common\Geodata\DomainRule::class);
        $this->domain = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes ip = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     * Generated from protobuf field <code>repeated bytes ip = 3;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIp($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->ip = $arr;

        return $this;
    }

    /**
     * ProxiedDomain indicates the mapped domain has the same IP address on this
     * domain. Xray will use this domain for IP queries.
     *
     * Generated from protobuf field <code>string proxied_domain = 4;</code>
     * @return string
     */
    public function getProxiedDomain()
    {
        return $this->proxied_domain;
    }

    /**
     * ProxiedDomain indicates the mapped domain has the same IP address on this
     * domain. Xray will use this domain for IP queries.
     *
     * Generated from protobuf field <code>string proxied_domain = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setProxiedDomain($var)
    {
        GPBUtil::checkString($var, True);
        $this->proxied_domain = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(HostMapping::class, \Xray\App\Dns\Config_HostMapping::class);

