<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/config.proto

namespace Xray\Transport\Internet;

use UnexpectedValueException;

/**
 * Protobuf type <code>xray.transport.internet.AddressPortStrategy</code>
 */
class AddressPortStrategy
{
    /**
     * Generated from protobuf enum <code>None = 0;</code>
     */
    const None = 0;
    /**
     * Generated from protobuf enum <code>SrvPortOnly = 1;</code>
     */
    const SrvPortOnly = 1;
    /**
     * Generated from protobuf enum <code>SrvAddressOnly = 2;</code>
     */
    const SrvAddressOnly = 2;
    /**
     * Generated from protobuf enum <code>SrvPortAndAddress = 3;</code>
     */
    const SrvPortAndAddress = 3;
    /**
     * Generated from protobuf enum <code>TxtPortOnly = 4;</code>
     */
    const TxtPortOnly = 4;
    /**
     * Generated from protobuf enum <code>TxtAddressOnly = 5;</code>
     */
    const TxtAddressOnly = 5;
    /**
     * Generated from protobuf enum <code>TxtPortAndAddress = 6;</code>
     */
    const TxtPortAndAddress = 6;

    private static $valueToName = [
        self::None => 'None',
        self::SrvPortOnly => 'SrvPortOnly',
        self::SrvAddressOnly => 'SrvAddressOnly',
        self::SrvPortAndAddress => 'SrvPortAndAddress',
        self::TxtPortOnly => 'TxtPortOnly',
        self::TxtAddressOnly => 'TxtAddressOnly',
        self::TxtPortAndAddress => 'TxtPortAndAddress',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

