<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/config.proto

namespace Xray\Transport\Internet;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.HappyEyeballsConfig</code>
 */
class HappyEyeballsConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool prioritize_ipv6 = 1;</code>
     */
    protected $prioritize_ipv6 = false;
    /**
     * Generated from protobuf field <code>uint32 interleave = 2;</code>
     */
    protected $interleave = 0;
    /**
     * Generated from protobuf field <code>uint64 try_delayMs = 3;</code>
     */
    protected $try_delayMs = 0;
    /**
     * Generated from protobuf field <code>uint32 max_concurrent_try = 4;</code>
     */
    protected $max_concurrent_try = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $prioritize_ipv6
     *     @type int $interleave
     *     @type int|string $try_delayMs
     *     @type int $max_concurrent_try
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool prioritize_ipv6 = 1;</code>
     * @return bool
     */
    public function getPrioritizeIpv6()
    {
        return $this->prioritize_ipv6;
    }

    /**
     * Generated from protobuf field <code>bool prioritize_ipv6 = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setPrioritizeIpv6($var)
    {
        GPBUtil::checkBool($var);
        $this->prioritize_ipv6 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 interleave = 2;</code>
     * @return int
     */
    public function getInterleave()
    {
        return $this->interleave;
    }

    /**
     * Generated from protobuf field <code>uint32 interleave = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setInterleave($var)
    {
        GPBUtil::checkUint32($var);
        $this->interleave = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 try_delayMs = 3;</code>
     * @return int|string
     */
    public function getTryDelayMs()
    {
        return $this->try_delayMs;
    }

    /**
     * Generated from protobuf field <code>uint64 try_delayMs = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTryDelayMs($var)
    {
        GPBUtil::checkUint64($var);
        $this->try_delayMs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 max_concurrent_try = 4;</code>
     * @return int
     */
    public function getMaxConcurrentTry()
    {
        return $this->max_concurrent_try;
    }

    /**
     * Generated from protobuf field <code>uint32 max_concurrent_try = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxConcurrentTry($var)
    {
        GPBUtil::checkUint32($var);
        $this->max_concurrent_try = $var;

        return $this;
    }

}

