<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/config.proto

namespace Xray\Transport\Internet;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.QuicParams</code>
 */
class QuicParams extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string congestion = 1;</code>
     */
    protected $congestion = '';
    /**
     * Generated from protobuf field <code>string bbr_profile = 2;</code>
     */
    protected $bbr_profile = '';
    /**
     * Generated from protobuf field <code>uint64 brutal_up = 3;</code>
     */
    protected $brutal_up = 0;
    /**
     * Generated from protobuf field <code>uint64 brutal_down = 4;</code>
     */
    protected $brutal_down = 0;
    /**
     * Generated from protobuf field <code>.xray.transport.internet.UdpHop udp_hop = 5;</code>
     */
    protected $udp_hop = null;
    /**
     * Generated from protobuf field <code>uint64 init_stream_receive_window = 6;</code>
     */
    protected $init_stream_receive_window = 0;
    /**
     * Generated from protobuf field <code>uint64 max_stream_receive_window = 7;</code>
     */
    protected $max_stream_receive_window = 0;
    /**
     * Generated from protobuf field <code>uint64 init_conn_receive_window = 8;</code>
     */
    protected $init_conn_receive_window = 0;
    /**
     * Generated from protobuf field <code>uint64 max_conn_receive_window = 9;</code>
     */
    protected $max_conn_receive_window = 0;
    /**
     * Generated from protobuf field <code>int64 max_idle_timeout = 10;</code>
     */
    protected $max_idle_timeout = 0;
    /**
     * Generated from protobuf field <code>int64 keep_alive_period = 11;</code>
     */
    protected $keep_alive_period = 0;
    /**
     * Generated from protobuf field <code>bool disable_path_mtu_discovery = 12;</code>
     */
    protected $disable_path_mtu_discovery = false;
    /**
     * Generated from protobuf field <code>int64 max_incoming_streams = 13;</code>
     */
    protected $max_incoming_streams = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $congestion
     *     @type string $bbr_profile
     *     @type int|string $brutal_up
     *     @type int|string $brutal_down
     *     @type \Xray\Transport\Internet\UdpHop $udp_hop
     *     @type int|string $init_stream_receive_window
     *     @type int|string $max_stream_receive_window
     *     @type int|string $init_conn_receive_window
     *     @type int|string $max_conn_receive_window
     *     @type int|string $max_idle_timeout
     *     @type int|string $keep_alive_period
     *     @type bool $disable_path_mtu_discovery
     *     @type int|string $max_incoming_streams
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string congestion = 1;</code>
     * @return string
     */
    public function getCongestion()
    {
        return $this->congestion;
    }

    /**
     * Generated from protobuf field <code>string congestion = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCongestion($var)
    {
        GPBUtil::checkString($var, True);
        $this->congestion = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bbr_profile = 2;</code>
     * @return string
     */
    public function getBbrProfile()
    {
        return $this->bbr_profile;
    }

    /**
     * Generated from protobuf field <code>string bbr_profile = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBbrProfile($var)
    {
        GPBUtil::checkString($var, True);
        $this->bbr_profile = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 brutal_up = 3;</code>
     * @return int|string
     */
    public function getBrutalUp()
    {
        return $this->brutal_up;
    }

    /**
     * Generated from protobuf field <code>uint64 brutal_up = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBrutalUp($var)
    {
        GPBUtil::checkUint64($var);
        $this->brutal_up = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 brutal_down = 4;</code>
     * @return int|string
     */
    public function getBrutalDown()
    {
        return $this->brutal_down;
    }

    /**
     * Generated from protobuf field <code>uint64 brutal_down = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBrutalDown($var)
    {
        GPBUtil::checkUint64($var);
        $this->brutal_down = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.UdpHop udp_hop = 5;</code>
     * @return \Xray\Transport\Internet\UdpHop|null
     */
    public function getUdpHop()
    {
        return $this->udp_hop;
    }

    public function hasUdpHop()
    {
        return isset($this->udp_hop);
    }

    public function clearUdpHop()
    {
        unset($this->udp_hop);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.UdpHop udp_hop = 5;</code>
     * @param \Xray\Transport\Internet\UdpHop $var
     * @return $this
     */
    public function setUdpHop($var)
    {
        GPBUtil::checkMessage($var, \Xray\Transport\Internet\UdpHop::class);
        $this->udp_hop = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 init_stream_receive_window = 6;</code>
     * @return int|string
     */
    public function getInitStreamReceiveWindow()
    {
        return $this->init_stream_receive_window;
    }

    /**
     * Generated from protobuf field <code>uint64 init_stream_receive_window = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setInitStreamReceiveWindow($var)
    {
        GPBUtil::checkUint64($var);
        $this->init_stream_receive_window = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 max_stream_receive_window = 7;</code>
     * @return int|string
     */
    public function getMaxStreamReceiveWindow()
    {
        return $this->max_stream_receive_window;
    }

    /**
     * Generated from protobuf field <code>uint64 max_stream_receive_window = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxStreamReceiveWindow($var)
    {
        GPBUtil::checkUint64($var);
        $this->max_stream_receive_window = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 init_conn_receive_window = 8;</code>
     * @return int|string
     */
    public function getInitConnReceiveWindow()
    {
        return $this->init_conn_receive_window;
    }

    /**
     * Generated from protobuf field <code>uint64 init_conn_receive_window = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setInitConnReceiveWindow($var)
    {
        GPBUtil::checkUint64($var);
        $this->init_conn_receive_window = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 max_conn_receive_window = 9;</code>
     * @return int|string
     */
    public function getMaxConnReceiveWindow()
    {
        return $this->max_conn_receive_window;
    }

    /**
     * Generated from protobuf field <code>uint64 max_conn_receive_window = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxConnReceiveWindow($var)
    {
        GPBUtil::checkUint64($var);
        $this->max_conn_receive_window = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 max_idle_timeout = 10;</code>
     * @return int|string
     */
    public function getMaxIdleTimeout()
    {
        return $this->max_idle_timeout;
    }

    /**
     * Generated from protobuf field <code>int64 max_idle_timeout = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxIdleTimeout($var)
    {
        GPBUtil::checkInt64($var);
        $this->max_idle_timeout = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 keep_alive_period = 11;</code>
     * @return int|string
     */
    public function getKeepAlivePeriod()
    {
        return $this->keep_alive_period;
    }

    /**
     * Generated from protobuf field <code>int64 keep_alive_period = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setKeepAlivePeriod($var)
    {
        GPBUtil::checkInt64($var);
        $this->keep_alive_period = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool disable_path_mtu_discovery = 12;</code>
     * @return bool
     */
    public function getDisablePathMtuDiscovery()
    {
        return $this->disable_path_mtu_discovery;
    }

    /**
     * Generated from protobuf field <code>bool disable_path_mtu_discovery = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setDisablePathMtuDiscovery($var)
    {
        GPBUtil::checkBool($var);
        $this->disable_path_mtu_discovery = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 max_incoming_streams = 13;</code>
     * @return int|string
     */
    public function getMaxIncomingStreams()
    {
        return $this->max_incoming_streams;
    }

    /**
     * Generated from protobuf field <code>int64 max_incoming_streams = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxIncomingStreams($var)
    {
        GPBUtil::checkInt64($var);
        $this->max_incoming_streams = $var;

        return $this;
    }

}

