<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/config.proto

namespace Xray\Transport\Internet;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.StreamConfig</code>
 */
class StreamConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.xray.common.net.IPOrDomain address = 8;</code>
     */
    protected $address = null;
    /**
     * Generated from protobuf field <code>uint32 port = 9;</code>
     */
    protected $port = 0;
    /**
     * Effective network.
     *
     * Generated from protobuf field <code>string protocol_name = 5;</code>
     */
    protected $protocol_name = '';
    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.TransportConfig transport_settings = 2;</code>
     */
    private $transport_settings;
    /**
     * Type of security. Must be a message name of the settings proto.
     *
     * Generated from protobuf field <code>string security_type = 3;</code>
     */
    protected $security_type = '';
    /**
     * Transport security settings. They can be either TLS or REALITY.
     *
     * Generated from protobuf field <code>repeated .xray.common.serial.TypedMessage security_settings = 4;</code>
     */
    private $security_settings;
    /**
     * Generated from protobuf field <code>repeated .xray.common.serial.TypedMessage udpmasks = 10;</code>
     */
    private $udpmasks;
    /**
     * Generated from protobuf field <code>repeated .xray.common.serial.TypedMessage tcpmasks = 11;</code>
     */
    private $tcpmasks;
    /**
     * Generated from protobuf field <code>.xray.transport.internet.QuicParams quic_params = 12;</code>
     */
    protected $quic_params = null;
    /**
     * Generated from protobuf field <code>.xray.transport.internet.SocketConfig socket_settings = 6;</code>
     */
    protected $socket_settings = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Xray\Common\Net\IPOrDomain $address
     *     @type int $port
     *     @type string $protocol_name
     *           Effective network.
     *     @type array<\Xray\Transport\Internet\TransportConfig>|\Google\Protobuf\Internal\RepeatedField $transport_settings
     *     @type string $security_type
     *           Type of security. Must be a message name of the settings proto.
     *     @type array<\Xray\Common\Serial\TypedMessage>|\Google\Protobuf\Internal\RepeatedField $security_settings
     *           Transport security settings. They can be either TLS or REALITY.
     *     @type array<\Xray\Common\Serial\TypedMessage>|\Google\Protobuf\Internal\RepeatedField $udpmasks
     *     @type array<\Xray\Common\Serial\TypedMessage>|\Google\Protobuf\Internal\RepeatedField $tcpmasks
     *     @type \Xray\Transport\Internet\QuicParams $quic_params
     *     @type \Xray\Transport\Internet\SocketConfig $socket_settings
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xray.common.net.IPOrDomain address = 8;</code>
     * @return \Xray\Common\Net\IPOrDomain|null
     */
    public function getAddress()
    {
        return $this->address;
    }

    public function hasAddress()
    {
        return isset($this->address);
    }

    public function clearAddress()
    {
        unset($this->address);
    }

    /**
     * Generated from protobuf field <code>.xray.common.net.IPOrDomain address = 8;</code>
     * @param \Xray\Common\Net\IPOrDomain $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, \Xray\Common\Net\IPOrDomain::class);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 port = 9;</code>
     * @return int
     */
    public function getPort()
    {
        return $this->port;
    }

    /**
     * Generated from protobuf field <code>uint32 port = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setPort($var)
    {
        GPBUtil::checkUint32($var);
        $this->port = $var;

        return $this;
    }

    /**
     * Effective network.
     *
     * Generated from protobuf field <code>string protocol_name = 5;</code>
     * @return string
     */
    public function getProtocolName()
    {
        return $this->protocol_name;
    }

    /**
     * Effective network.
     *
     * Generated from protobuf field <code>string protocol_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setProtocolName($var)
    {
        GPBUtil::checkString($var, True);
        $this->protocol_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.TransportConfig transport_settings = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTransportSettings()
    {
        return $this->transport_settings;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.TransportConfig transport_settings = 2;</code>
     * @param array<\Xray\Transport\Internet\TransportConfig>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTransportSettings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Transport\Internet\TransportConfig::class);
        $this->transport_settings = $arr;

        return $this;
    }

    /**
     * Type of security. Must be a message name of the settings proto.
     *
     * Generated from protobuf field <code>string security_type = 3;</code>
     * @return string
     */
    public function getSecurityType()
    {
        return $this->security_type;
    }

    /**
     * Type of security. Must be a message name of the settings proto.
     *
     * Generated from protobuf field <code>string security_type = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSecurityType($var)
    {
        GPBUtil::checkString($var, True);
        $this->security_type = $var;

        return $this;
    }

    /**
     * Transport security settings. They can be either TLS or REALITY.
     *
     * Generated from protobuf field <code>repeated .xray.common.serial.TypedMessage security_settings = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSecuritySettings()
    {
        return $this->security_settings;
    }

    /**
     * Transport security settings. They can be either TLS or REALITY.
     *
     * Generated from protobuf field <code>repeated .xray.common.serial.TypedMessage security_settings = 4;</code>
     * @param array<\Xray\Common\Serial\TypedMessage>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSecuritySettings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Common\Serial\TypedMessage::class);
        $this->security_settings = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.serial.TypedMessage udpmasks = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUdpmasks()
    {
        return $this->udpmasks;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.serial.TypedMessage udpmasks = 10;</code>
     * @param array<\Xray\Common\Serial\TypedMessage>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUdpmasks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Common\Serial\TypedMessage::class);
        $this->udpmasks = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.serial.TypedMessage tcpmasks = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTcpmasks()
    {
        return $this->tcpmasks;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.common.serial.TypedMessage tcpmasks = 11;</code>
     * @param array<\Xray\Common\Serial\TypedMessage>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTcpmasks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Common\Serial\TypedMessage::class);
        $this->tcpmasks = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.QuicParams quic_params = 12;</code>
     * @return \Xray\Transport\Internet\QuicParams|null
     */
    public function getQuicParams()
    {
        return $this->quic_params;
    }

    public function hasQuicParams()
    {
        return isset($this->quic_params);
    }

    public function clearQuicParams()
    {
        unset($this->quic_params);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.QuicParams quic_params = 12;</code>
     * @param \Xray\Transport\Internet\QuicParams $var
     * @return $this
     */
    public function setQuicParams($var)
    {
        GPBUtil::checkMessage($var, \Xray\Transport\Internet\QuicParams::class);
        $this->quic_params = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.SocketConfig socket_settings = 6;</code>
     * @return \Xray\Transport\Internet\SocketConfig|null
     */
    public function getSocketSettings()
    {
        return $this->socket_settings;
    }

    public function hasSocketSettings()
    {
        return isset($this->socket_settings);
    }

    public function clearSocketSettings()
    {
        unset($this->socket_settings);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.SocketConfig socket_settings = 6;</code>
     * @param \Xray\Transport\Internet\SocketConfig $var
     * @return $this
     */
    public function setSocketSettings($var)
    {
        GPBUtil::checkMessage($var, \Xray\Transport\Internet\SocketConfig::class);
        $this->socket_settings = $var;

        return $this;
    }

}

