<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/config.proto

namespace Xray\Transport\Internet;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.UdpHop</code>
 */
class UdpHop extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated uint32 ports = 1;</code>
     */
    private $ports;
    /**
     * Generated from protobuf field <code>int64 interval_min = 2;</code>
     */
    protected $interval_min = 0;
    /**
     * Generated from protobuf field <code>int64 interval_max = 3;</code>
     */
    protected $interval_max = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $ports
     *     @type int|string $interval_min
     *     @type int|string $interval_max
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated uint32 ports = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPorts()
    {
        return $this->ports;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 ports = 1;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPorts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->ports = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 interval_min = 2;</code>
     * @return int|string
     */
    public function getIntervalMin()
    {
        return $this->interval_min;
    }

    /**
     * Generated from protobuf field <code>int64 interval_min = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIntervalMin($var)
    {
        GPBUtil::checkInt64($var);
        $this->interval_min = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 interval_max = 3;</code>
     * @return int|string
     */
    public function getIntervalMax()
    {
        return $this->interval_max;
    }

    /**
     * Generated from protobuf field <code>int64 interval_max = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIntervalMax($var)
    {
        GPBUtil::checkInt64($var);
        $this->interval_max = $var;

        return $this;
    }

}

