<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/vless/account.proto

namespace Xray\Proxy\Vless;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.proxy.vless.Account</code>
 */
class Account extends \Google\Protobuf\Internal\Message
{
    /**
     * ID of the account, in the form of a UUID, e.g., "66ad4540-b58c-4ad2-9926-ea63445a9b57".
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Flow settings. May be "xtls-rprx-vision".
     *
     * Generated from protobuf field <code>string flow = 2;</code>
     */
    protected $flow = '';
    /**
     * Generated from protobuf field <code>string encryption = 3;</code>
     */
    protected $encryption = '';
    /**
     * Generated from protobuf field <code>uint32 xorMode = 4;</code>
     */
    protected $xorMode = 0;
    /**
     * Generated from protobuf field <code>uint32 seconds = 5;</code>
     */
    protected $seconds = 0;
    /**
     * Generated from protobuf field <code>string padding = 6;</code>
     */
    protected $padding = '';
    /**
     * Generated from protobuf field <code>.xray.proxy.vless.Reverse reverse = 7;</code>
     */
    protected $reverse = null;
    /**
     * Generated from protobuf field <code>uint32 testpre = 8;</code>
     */
    protected $testpre = 0;
    /**
     * Generated from protobuf field <code>repeated uint32 testseed = 9;</code>
     */
    private $testseed;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           ID of the account, in the form of a UUID, e.g., "66ad4540-b58c-4ad2-9926-ea63445a9b57".
     *     @type string $flow
     *           Flow settings. May be "xtls-rprx-vision".
     *     @type string $encryption
     *     @type int $xorMode
     *     @type int $seconds
     *     @type string $padding
     *     @type \Xray\Proxy\Vless\Reverse $reverse
     *     @type int $testpre
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $testseed
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Vless\Account::initOnce();
        parent::__construct($data);
    }

    /**
     * ID of the account, in the form of a UUID, e.g., "66ad4540-b58c-4ad2-9926-ea63445a9b57".
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * ID of the account, in the form of a UUID, e.g., "66ad4540-b58c-4ad2-9926-ea63445a9b57".
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Flow settings. May be "xtls-rprx-vision".
     *
     * Generated from protobuf field <code>string flow = 2;</code>
     * @return string
     */
    public function getFlow()
    {
        return $this->flow;
    }

    /**
     * Flow settings. May be "xtls-rprx-vision".
     *
     * Generated from protobuf field <code>string flow = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFlow($var)
    {
        GPBUtil::checkString($var, True);
        $this->flow = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string encryption = 3;</code>
     * @return string
     */
    public function getEncryption()
    {
        return $this->encryption;
    }

    /**
     * Generated from protobuf field <code>string encryption = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEncryption($var)
    {
        GPBUtil::checkString($var, True);
        $this->encryption = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 xorMode = 4;</code>
     * @return int
     */
    public function getXorMode()
    {
        return $this->xorMode;
    }

    /**
     * Generated from protobuf field <code>uint32 xorMode = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setXorMode($var)
    {
        GPBUtil::checkUint32($var);
        $this->xorMode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 seconds = 5;</code>
     * @return int
     */
    public function getSeconds()
    {
        return $this->seconds;
    }

    /**
     * Generated from protobuf field <code>uint32 seconds = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setSeconds($var)
    {
        GPBUtil::checkUint32($var);
        $this->seconds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string padding = 6;</code>
     * @return string
     */
    public function getPadding()
    {
        return $this->padding;
    }

    /**
     * Generated from protobuf field <code>string padding = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPadding($var)
    {
        GPBUtil::checkString($var, True);
        $this->padding = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.proxy.vless.Reverse reverse = 7;</code>
     * @return \Xray\Proxy\Vless\Reverse|null
     */
    public function getReverse()
    {
        return $this->reverse;
    }

    public function hasReverse()
    {
        return isset($this->reverse);
    }

    public function clearReverse()
    {
        unset($this->reverse);
    }

    /**
     * Generated from protobuf field <code>.xray.proxy.vless.Reverse reverse = 7;</code>
     * @param \Xray\Proxy\Vless\Reverse $var
     * @return $this
     */
    public function setReverse($var)
    {
        GPBUtil::checkMessage($var, \Xray\Proxy\Vless\Reverse::class);
        $this->reverse = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 testpre = 8;</code>
     * @return int
     */
    public function getTestpre()
    {
        return $this->testpre;
    }

    /**
     * Generated from protobuf field <code>uint32 testpre = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setTestpre($var)
    {
        GPBUtil::checkUint32($var);
        $this->testpre = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 testseed = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTestseed()
    {
        return $this->testseed;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 testseed = 9;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTestseed($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->testseed = $arr;

        return $this;
    }

}

