<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/vless/account.proto

namespace Xray\Proxy\Vless;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.proxy.vless.Reverse</code>
 */
class Reverse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string tag = 1;</code>
     */
    protected $tag = '';
    /**
     * Generated from protobuf field <code>.xray.app.proxyman.SniffingConfig sniffing = 2;</code>
     */
    protected $sniffing = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tag
     *     @type \Xray\App\Proxyman\SniffingConfig $sniffing
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Vless\Account::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string tag = 1;</code>
     * @return string
     */
    public function getTag()
    {
        return $this->tag;
    }

    /**
     * Generated from protobuf field <code>string tag = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->tag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.app.proxyman.SniffingConfig sniffing = 2;</code>
     * @return \Xray\App\Proxyman\SniffingConfig|null
     */
    public function getSniffing()
    {
        return $this->sniffing;
    }

    public function hasSniffing()
    {
        return isset($this->sniffing);
    }

    public function clearSniffing()
    {
        unset($this->sniffing);
    }

    /**
     * Generated from protobuf field <code>.xray.app.proxyman.SniffingConfig sniffing = 2;</code>
     * @param \Xray\App\Proxyman\SniffingConfig $var
     * @return $this
     */
    public function setSniffing($var)
    {
        GPBUtil::checkMessage($var, \Xray\App\Proxyman\SniffingConfig::class);
        $this->sniffing = $var;

        return $this;
    }

}

