<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/hysteria/account/config.proto

namespace Xray\Proxy\Hysteria\Account;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.proxy.hysteria.account.Account</code>
 */
class Account extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string auth = 1;</code>
     */
    protected $auth = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $auth
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Hysteria\Account\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string auth = 1;</code>
     * @return string
     */
    public function getAuth()
    {
        return $this->auth;
    }

    /**
     * Generated from protobuf field <code>string auth = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAuth($var)
    {
        GPBUtil::checkString($var, True);
        $this->auth = $var;

        return $this;
    }

}

