<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/finalmask/fragment/config.proto

namespace Xray\Transport\Internet\Finalmask\Fragment;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.finalmask.fragment.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 packets_from = 1;</code>
     */
    protected $packets_from = 0;
    /**
     * Generated from protobuf field <code>int64 packets_to = 2;</code>
     */
    protected $packets_to = 0;
    /**
     * Generated from protobuf field <code>int64 length_min = 3;</code>
     */
    protected $length_min = 0;
    /**
     * Generated from protobuf field <code>int64 length_max = 4;</code>
     */
    protected $length_max = 0;
    /**
     * Generated from protobuf field <code>int64 delay_min = 5;</code>
     */
    protected $delay_min = 0;
    /**
     * Generated from protobuf field <code>int64 delay_max = 6;</code>
     */
    protected $delay_max = 0;
    /**
     * Generated from protobuf field <code>int64 max_split_min = 7;</code>
     */
    protected $max_split_min = 0;
    /**
     * Generated from protobuf field <code>int64 max_split_max = 8;</code>
     */
    protected $max_split_max = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $packets_from
     *     @type int|string $packets_to
     *     @type int|string $length_min
     *     @type int|string $length_max
     *     @type int|string $delay_min
     *     @type int|string $delay_max
     *     @type int|string $max_split_min
     *     @type int|string $max_split_max
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Finalmask\Fragment\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 packets_from = 1;</code>
     * @return int|string
     */
    public function getPacketsFrom()
    {
        return $this->packets_from;
    }

    /**
     * Generated from protobuf field <code>int64 packets_from = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPacketsFrom($var)
    {
        GPBUtil::checkInt64($var);
        $this->packets_from = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 packets_to = 2;</code>
     * @return int|string
     */
    public function getPacketsTo()
    {
        return $this->packets_to;
    }

    /**
     * Generated from protobuf field <code>int64 packets_to = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPacketsTo($var)
    {
        GPBUtil::checkInt64($var);
        $this->packets_to = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 length_min = 3;</code>
     * @return int|string
     */
    public function getLengthMin()
    {
        return $this->length_min;
    }

    /**
     * Generated from protobuf field <code>int64 length_min = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLengthMin($var)
    {
        GPBUtil::checkInt64($var);
        $this->length_min = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 length_max = 4;</code>
     * @return int|string
     */
    public function getLengthMax()
    {
        return $this->length_max;
    }

    /**
     * Generated from protobuf field <code>int64 length_max = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLengthMax($var)
    {
        GPBUtil::checkInt64($var);
        $this->length_max = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 delay_min = 5;</code>
     * @return int|string
     */
    public function getDelayMin()
    {
        return $this->delay_min;
    }

    /**
     * Generated from protobuf field <code>int64 delay_min = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDelayMin($var)
    {
        GPBUtil::checkInt64($var);
        $this->delay_min = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 delay_max = 6;</code>
     * @return int|string
     */
    public function getDelayMax()
    {
        return $this->delay_max;
    }

    /**
     * Generated from protobuf field <code>int64 delay_max = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDelayMax($var)
    {
        GPBUtil::checkInt64($var);
        $this->delay_max = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 max_split_min = 7;</code>
     * @return int|string
     */
    public function getMaxSplitMin()
    {
        return $this->max_split_min;
    }

    /**
     * Generated from protobuf field <code>int64 max_split_min = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxSplitMin($var)
    {
        GPBUtil::checkInt64($var);
        $this->max_split_min = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 max_split_max = 8;</code>
     * @return int|string
     */
    public function getMaxSplitMax()
    {
        return $this->max_split_max;
    }

    /**
     * Generated from protobuf field <code>int64 max_split_max = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxSplitMax($var)
    {
        GPBUtil::checkInt64($var);
        $this->max_split_max = $var;

        return $this;
    }

}

