<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/finalmask/header/custom/config.proto

namespace Xray\Transport\Internet\Finalmask\Header\Custom;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.finalmask.header.custom.ExprArg</code>
 */
class ExprArg extends \Google\Protobuf\Internal\Message
{
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $bytes
     *     @type int|string $u64
     *     @type string $var
     *     @type string $metadata
     *     @type \Xray\Transport\Internet\Finalmask\Header\Custom\Expr $expr
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Finalmask\Header\Custom\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes bytes = 1;</code>
     * @return string
     */
    public function getBytes()
    {
        return $this->readOneof(1);
    }

    public function hasBytes()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>bytes bytes = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBytes($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 u64 = 2;</code>
     * @return int|string
     */
    public function getU64()
    {
        return $this->readOneof(2);
    }

    public function hasU64()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>uint64 u64 = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setU64($var)
    {
        GPBUtil::checkUint64($var);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string var = 3;</code>
     * @return string
     */
    public function getVar()
    {
        return $this->readOneof(3);
    }

    public function hasVar()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>string var = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setVar($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string metadata = 4;</code>
     * @return string
     */
    public function getMetadata()
    {
        return $this->readOneof(4);
    }

    public function hasMetadata()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>string metadata = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMetadata($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.finalmask.header.custom.Expr expr = 5;</code>
     * @return \Xray\Transport\Internet\Finalmask\Header\Custom\Expr|null
     */
    public function getExpr()
    {
        return $this->readOneof(5);
    }

    public function hasExpr()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.finalmask.header.custom.Expr expr = 5;</code>
     * @param \Xray\Transport\Internet\Finalmask\Header\Custom\Expr $var
     * @return $this
     */
    public function setExpr($var)
    {
        GPBUtil::checkMessage($var, \Xray\Transport\Internet\Finalmask\Header\Custom\Expr::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

