<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/finalmask/header/custom/config.proto

namespace Xray\Transport\Internet\Finalmask\Header\Custom;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.finalmask.header.custom.Expr</code>
 */
class Expr extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string op = 1;</code>
     */
    protected $op = '';
    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.finalmask.header.custom.ExprArg args = 2;</code>
     */
    private $args;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $op
     *     @type array<\Xray\Transport\Internet\Finalmask\Header\Custom\ExprArg>|\Google\Protobuf\Internal\RepeatedField $args
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Finalmask\Header\Custom\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string op = 1;</code>
     * @return string
     */
    public function getOp()
    {
        return $this->op;
    }

    /**
     * Generated from protobuf field <code>string op = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOp($var)
    {
        GPBUtil::checkString($var, True);
        $this->op = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.finalmask.header.custom.ExprArg args = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getArgs()
    {
        return $this->args;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.finalmask.header.custom.ExprArg args = 2;</code>
     * @param array<\Xray\Transport\Internet\Finalmask\Header\Custom\ExprArg>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setArgs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Transport\Internet\Finalmask\Header\Custom\ExprArg::class);
        $this->args = $arr;

        return $this;
    }

}

