<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/finalmask/header/custom/config.proto

namespace Xray\Transport\Internet\Finalmask\Header\Custom;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.finalmask.header.custom.TCPConfig</code>
 */
class TCPConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.finalmask.header.custom.TCPSequence clients = 1;</code>
     */
    private $clients;
    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.finalmask.header.custom.TCPSequence servers = 2;</code>
     */
    private $servers;
    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.finalmask.header.custom.TCPSequence errors = 3;</code>
     */
    private $errors;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Xray\Transport\Internet\Finalmask\Header\Custom\TCPSequence>|\Google\Protobuf\Internal\RepeatedField $clients
     *     @type array<\Xray\Transport\Internet\Finalmask\Header\Custom\TCPSequence>|\Google\Protobuf\Internal\RepeatedField $servers
     *     @type array<\Xray\Transport\Internet\Finalmask\Header\Custom\TCPSequence>|\Google\Protobuf\Internal\RepeatedField $errors
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Finalmask\Header\Custom\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.finalmask.header.custom.TCPSequence clients = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getClients()
    {
        return $this->clients;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.finalmask.header.custom.TCPSequence clients = 1;</code>
     * @param array<\Xray\Transport\Internet\Finalmask\Header\Custom\TCPSequence>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setClients($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Transport\Internet\Finalmask\Header\Custom\TCPSequence::class);
        $this->clients = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.finalmask.header.custom.TCPSequence servers = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getServers()
    {
        return $this->servers;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.finalmask.header.custom.TCPSequence servers = 2;</code>
     * @param array<\Xray\Transport\Internet\Finalmask\Header\Custom\TCPSequence>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setServers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Transport\Internet\Finalmask\Header\Custom\TCPSequence::class);
        $this->servers = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.finalmask.header.custom.TCPSequence errors = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getErrors()
    {
        return $this->errors;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.finalmask.header.custom.TCPSequence errors = 3;</code>
     * @param array<\Xray\Transport\Internet\Finalmask\Header\Custom\TCPSequence>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setErrors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Transport\Internet\Finalmask\Header\Custom\TCPSequence::class);
        $this->errors = $arr;

        return $this;
    }

}

