<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/finalmask/header/custom/config.proto

namespace Xray\Transport\Internet\Finalmask\Header\Custom;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.finalmask.header.custom.TCPSequence</code>
 */
class TCPSequence extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.finalmask.header.custom.TCPItem sequence = 1;</code>
     */
    private $sequence;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Xray\Transport\Internet\Finalmask\Header\Custom\TCPItem>|\Google\Protobuf\Internal\RepeatedField $sequence
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Finalmask\Header\Custom\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.finalmask.header.custom.TCPItem sequence = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSequence()
    {
        return $this->sequence;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.finalmask.header.custom.TCPItem sequence = 1;</code>
     * @param array<\Xray\Transport\Internet\Finalmask\Header\Custom\TCPItem>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSequence($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Transport\Internet\Finalmask\Header\Custom\TCPItem::class);
        $this->sequence = $arr;

        return $this;
    }

}

