<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/finalmask/header/custom/config.proto

namespace Xray\Transport\Internet\Finalmask\Header\Custom;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.finalmask.header.custom.UDPConfig</code>
 */
class UDPConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.finalmask.header.custom.UDPItem client = 1;</code>
     */
    private $client;
    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.finalmask.header.custom.UDPItem server = 2;</code>
     */
    private $server;
    /**
     * Generated from protobuf field <code>string mode = 3;</code>
     */
    protected $mode = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Xray\Transport\Internet\Finalmask\Header\Custom\UDPItem>|\Google\Protobuf\Internal\RepeatedField $client
     *     @type array<\Xray\Transport\Internet\Finalmask\Header\Custom\UDPItem>|\Google\Protobuf\Internal\RepeatedField $server
     *     @type string $mode
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Finalmask\Header\Custom\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.finalmask.header.custom.UDPItem client = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getClient()
    {
        return $this->client;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.finalmask.header.custom.UDPItem client = 1;</code>
     * @param array<\Xray\Transport\Internet\Finalmask\Header\Custom\UDPItem>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setClient($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Transport\Internet\Finalmask\Header\Custom\UDPItem::class);
        $this->client = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.finalmask.header.custom.UDPItem server = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getServer()
    {
        return $this->server;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.transport.internet.finalmask.header.custom.UDPItem server = 2;</code>
     * @param array<\Xray\Transport\Internet\Finalmask\Header\Custom\UDPItem>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setServer($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Transport\Internet\Finalmask\Header\Custom\UDPItem::class);
        $this->server = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mode = 3;</code>
     * @return string
     */
    public function getMode()
    {
        return $this->mode;
    }

    /**
     * Generated from protobuf field <code>string mode = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMode($var)
    {
        GPBUtil::checkString($var, True);
        $this->mode = $var;

        return $this;
    }

}

