<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/finalmask/header/custom/config.proto

namespace Xray\Transport\Internet\Finalmask\Header\Custom;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.finalmask.header.custom.UDPItem</code>
 */
class UDPItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 rand = 1;</code>
     */
    protected $rand = 0;
    /**
     * Generated from protobuf field <code>int32 rand_min = 2;</code>
     */
    protected $rand_min = 0;
    /**
     * Generated from protobuf field <code>int32 rand_max = 3;</code>
     */
    protected $rand_max = 0;
    /**
     * Generated from protobuf field <code>bytes packet = 4;</code>
     */
    protected $packet = '';
    /**
     * Generated from protobuf field <code>string save = 5;</code>
     */
    protected $save = '';
    /**
     * Generated from protobuf field <code>string var = 6;</code>
     */
    protected $var = '';
    /**
     * Generated from protobuf field <code>.xray.transport.internet.finalmask.header.custom.Expr expr = 7;</code>
     */
    protected $expr = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $rand
     *     @type int $rand_min
     *     @type int $rand_max
     *     @type string $packet
     *     @type string $save
     *     @type string $var
     *     @type \Xray\Transport\Internet\Finalmask\Header\Custom\Expr $expr
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Finalmask\Header\Custom\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 rand = 1;</code>
     * @return int
     */
    public function getRand()
    {
        return $this->rand;
    }

    /**
     * Generated from protobuf field <code>int32 rand = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRand($var)
    {
        GPBUtil::checkInt32($var);
        $this->rand = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 rand_min = 2;</code>
     * @return int
     */
    public function getRandMin()
    {
        return $this->rand_min;
    }

    /**
     * Generated from protobuf field <code>int32 rand_min = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRandMin($var)
    {
        GPBUtil::checkInt32($var);
        $this->rand_min = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 rand_max = 3;</code>
     * @return int
     */
    public function getRandMax()
    {
        return $this->rand_max;
    }

    /**
     * Generated from protobuf field <code>int32 rand_max = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setRandMax($var)
    {
        GPBUtil::checkInt32($var);
        $this->rand_max = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes packet = 4;</code>
     * @return string
     */
    public function getPacket()
    {
        return $this->packet;
    }

    /**
     * Generated from protobuf field <code>bytes packet = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPacket($var)
    {
        GPBUtil::checkString($var, False);
        $this->packet = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string save = 5;</code>
     * @return string
     */
    public function getSave()
    {
        return $this->save;
    }

    /**
     * Generated from protobuf field <code>string save = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSave($var)
    {
        GPBUtil::checkString($var, True);
        $this->save = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string var = 6;</code>
     * @return string
     */
    public function getVar()
    {
        return $this->var;
    }

    /**
     * Generated from protobuf field <code>string var = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setVar($var)
    {
        GPBUtil::checkString($var, True);
        $this->var = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.finalmask.header.custom.Expr expr = 7;</code>
     * @return \Xray\Transport\Internet\Finalmask\Header\Custom\Expr|null
     */
    public function getExpr()
    {
        return $this->expr;
    }

    public function hasExpr()
    {
        return isset($this->expr);
    }

    public function clearExpr()
    {
        unset($this->expr);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.finalmask.header.custom.Expr expr = 7;</code>
     * @param \Xray\Transport\Internet\Finalmask\Header\Custom\Expr $var
     * @return $this
     */
    public function setExpr($var)
    {
        GPBUtil::checkMessage($var, \Xray\Transport\Internet\Finalmask\Header\Custom\Expr::class);
        $this->expr = $var;

        return $this;
    }

}

