<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/finalmask/xdns/config.proto

namespace Xray\Transport\Internet\Finalmask\Xdns;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.finalmask.xdns.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string domains = 1;</code>
     */
    private $domains;
    /**
     * Generated from protobuf field <code>repeated string resolvers = 2;</code>
     */
    private $resolvers;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $domains
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $resolvers
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Finalmask\Xdns\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string domains = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDomains()
    {
        return $this->domains;
    }

    /**
     * Generated from protobuf field <code>repeated string domains = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDomains($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->domains = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string resolvers = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResolvers()
    {
        return $this->resolvers;
    }

    /**
     * Generated from protobuf field <code>repeated string resolvers = 2;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResolvers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->resolvers = $arr;

        return $this;
    }

}

