<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/finalmask/mkcp/aes128gcm/config.proto

namespace GPBMetadata\Transport\Internet\Finalmask\Mkcp\Aes128Gcm;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Å
8transport/internet/finalmask/mkcp/aes128gcm/config.proto0xray.transport.internet.finalmask.mkcp.aes128gcm"
Config
password (	B²
4com.xray.transport.internet.finalmask.mkcp.aes128gcmPZEgithub.com/xtls/xray-core/transport/internet/finalmask/mkcp/aes128gcmª0Xray.Transport.Internet.Finalmask.Mkcp.Aes128Gcmbproto3'
        , true);

        static::$is_initialized = true;
    }
}

