<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/hysteria/config.proto

namespace Xray\Proxy\Hysteria;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.proxy.hysteria.ClientConfig</code>
 */
class ClientConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 version = 1;</code>
     */
    protected $version = 0;
    /**
     * Generated from protobuf field <code>.xray.common.protocol.ServerEndpoint server = 2;</code>
     */
    protected $server = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $version
     *     @type \Xray\Common\Protocol\ServerEndpoint $server
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Hysteria\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 version = 1;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>int32 version = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.common.protocol.ServerEndpoint server = 2;</code>
     * @return \Xray\Common\Protocol\ServerEndpoint|null
     */
    public function getServer()
    {
        return $this->server;
    }

    public function hasServer()
    {
        return isset($this->server);
    }

    public function clearServer()
    {
        unset($this->server);
    }

    /**
     * Generated from protobuf field <code>.xray.common.protocol.ServerEndpoint server = 2;</code>
     * @param \Xray\Common\Protocol\ServerEndpoint $var
     * @return $this
     */
    public function setServer($var)
    {
        GPBUtil::checkMessage($var, \Xray\Common\Protocol\ServerEndpoint::class);
        $this->server = $var;

        return $this;
    }

}

