<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/tls/config.proto

namespace Xray\Transport\Internet\Tls;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.tls.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool allow_insecure = 1;</code>
     */
    protected $allow_insecure = false;
    /**
     * List of certificates to be served on server.
     *
     * Generated from protobuf field <code>repeated .xray.transport.internet.tls.Certificate certificate = 2;</code>
     */
    private $certificate;
    /**
     * Override server name.
     *
     * Generated from protobuf field <code>string server_name = 3;</code>
     */
    protected $server_name = '';
    /**
     * Lists of string as ALPN values.
     *
     * Generated from protobuf field <code>repeated string next_protocol = 4;</code>
     */
    private $next_protocol;
    /**
     * Whether or not to enable session (ticket) resumption.
     *
     * Generated from protobuf field <code>bool enable_session_resumption = 5;</code>
     */
    protected $enable_session_resumption = false;
    /**
     * If true, root certificates on the system will not be loaded for
     * verification.
     *
     * Generated from protobuf field <code>bool disable_system_root = 6;</code>
     */
    protected $disable_system_root = false;
    /**
     * The minimum TLS version.
     *
     * Generated from protobuf field <code>string min_version = 7;</code>
     */
    protected $min_version = '';
    /**
     * The maximum TLS version.
     *
     * Generated from protobuf field <code>string max_version = 8;</code>
     */
    protected $max_version = '';
    /**
     * Specify cipher suites, except for TLS 1.3.
     *
     * Generated from protobuf field <code>string cipher_suites = 9;</code>
     */
    protected $cipher_suites = '';
    /**
     * TLS Client Hello fingerprint (uTLS).
     *
     * Generated from protobuf field <code>string fingerprint = 11;</code>
     */
    protected $fingerprint = '';
    /**
     * Generated from protobuf field <code>bool reject_unknown_sni = 12;</code>
     */
    protected $reject_unknown_sni = false;
    /**
     * Generated from protobuf field <code>string master_key_log = 15;</code>
     */
    protected $master_key_log = '';
    /**
     * Lists of string as CurvePreferences values.
     *
     * Generated from protobuf field <code>repeated string curve_preferences = 16;</code>
     */
    private $curve_preferences;
    /**
     * Generated from protobuf field <code>repeated string verify_peer_cert_by_name = 17;</code>
     */
    private $verify_peer_cert_by_name;
    /**
     * Generated from protobuf field <code>bytes ech_server_keys = 18;</code>
     */
    protected $ech_server_keys = '';
    /**
     * Generated from protobuf field <code>string ech_config_list = 19;</code>
     */
    protected $ech_config_list = '';
    /**
     * Deprecated
     *
     * Generated from protobuf field <code>string ech_force_query = 20;</code>
     */
    protected $ech_force_query = '';
    /**
     * Generated from protobuf field <code>.xray.transport.internet.SocketConfig ech_socket_settings = 21;</code>
     */
    protected $ech_socket_settings = null;
    /**
     * Generated from protobuf field <code>repeated bytes pinned_peer_cert_sha256 = 22;</code>
     */
    private $pinned_peer_cert_sha256;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $allow_insecure
     *     @type array<\Xray\Transport\Internet\Tls\Certificate>|\Google\Protobuf\Internal\RepeatedField $certificate
     *           List of certificates to be served on server.
     *     @type string $server_name
     *           Override server name.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $next_protocol
     *           Lists of string as ALPN values.
     *     @type bool $enable_session_resumption
     *           Whether or not to enable session (ticket) resumption.
     *     @type bool $disable_system_root
     *           If true, root certificates on the system will not be loaded for
     *           verification.
     *     @type string $min_version
     *           The minimum TLS version.
     *     @type string $max_version
     *           The maximum TLS version.
     *     @type string $cipher_suites
     *           Specify cipher suites, except for TLS 1.3.
     *     @type string $fingerprint
     *           TLS Client Hello fingerprint (uTLS).
     *     @type bool $reject_unknown_sni
     *     @type string $master_key_log
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $curve_preferences
     *           Lists of string as CurvePreferences values.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $verify_peer_cert_by_name
     *     @type string $ech_server_keys
     *     @type string $ech_config_list
     *     @type string $ech_force_query
     *           Deprecated
     *     @type \Xray\Transport\Internet\SocketConfig $ech_socket_settings
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $pinned_peer_cert_sha256
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Tls\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool allow_insecure = 1;</code>
     * @return bool
     */
    public function getAllowInsecure()
    {
        return $this->allow_insecure;
    }

    /**
     * Generated from protobuf field <code>bool allow_insecure = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setAllowInsecure($var)
    {
        GPBUtil::checkBool($var);
        $this->allow_insecure = $var;

        return $this;
    }

    /**
     * List of certificates to be served on server.
     *
     * Generated from protobuf field <code>repeated .xray.transport.internet.tls.Certificate certificate = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCertificate()
    {
        return $this->certificate;
    }

    /**
     * List of certificates to be served on server.
     *
     * Generated from protobuf field <code>repeated .xray.transport.internet.tls.Certificate certificate = 2;</code>
     * @param array<\Xray\Transport\Internet\Tls\Certificate>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCertificate($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\Transport\Internet\Tls\Certificate::class);
        $this->certificate = $arr;

        return $this;
    }

    /**
     * Override server name.
     *
     * Generated from protobuf field <code>string server_name = 3;</code>
     * @return string
     */
    public function getServerName()
    {
        return $this->server_name;
    }

    /**
     * Override server name.
     *
     * Generated from protobuf field <code>string server_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setServerName($var)
    {
        GPBUtil::checkString($var, True);
        $this->server_name = $var;

        return $this;
    }

    /**
     * Lists of string as ALPN values.
     *
     * Generated from protobuf field <code>repeated string next_protocol = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNextProtocol()
    {
        return $this->next_protocol;
    }

    /**
     * Lists of string as ALPN values.
     *
     * Generated from protobuf field <code>repeated string next_protocol = 4;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNextProtocol($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->next_protocol = $arr;

        return $this;
    }

    /**
     * Whether or not to enable session (ticket) resumption.
     *
     * Generated from protobuf field <code>bool enable_session_resumption = 5;</code>
     * @return bool
     */
    public function getEnableSessionResumption()
    {
        return $this->enable_session_resumption;
    }

    /**
     * Whether or not to enable session (ticket) resumption.
     *
     * Generated from protobuf field <code>bool enable_session_resumption = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnableSessionResumption($var)
    {
        GPBUtil::checkBool($var);
        $this->enable_session_resumption = $var;

        return $this;
    }

    /**
     * If true, root certificates on the system will not be loaded for
     * verification.
     *
     * Generated from protobuf field <code>bool disable_system_root = 6;</code>
     * @return bool
     */
    public function getDisableSystemRoot()
    {
        return $this->disable_system_root;
    }

    /**
     * If true, root certificates on the system will not be loaded for
     * verification.
     *
     * Generated from protobuf field <code>bool disable_system_root = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setDisableSystemRoot($var)
    {
        GPBUtil::checkBool($var);
        $this->disable_system_root = $var;

        return $this;
    }

    /**
     * The minimum TLS version.
     *
     * Generated from protobuf field <code>string min_version = 7;</code>
     * @return string
     */
    public function getMinVersion()
    {
        return $this->min_version;
    }

    /**
     * The minimum TLS version.
     *
     * Generated from protobuf field <code>string min_version = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setMinVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->min_version = $var;

        return $this;
    }

    /**
     * The maximum TLS version.
     *
     * Generated from protobuf field <code>string max_version = 8;</code>
     * @return string
     */
    public function getMaxVersion()
    {
        return $this->max_version;
    }

    /**
     * The maximum TLS version.
     *
     * Generated from protobuf field <code>string max_version = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setMaxVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->max_version = $var;

        return $this;
    }

    /**
     * Specify cipher suites, except for TLS 1.3.
     *
     * Generated from protobuf field <code>string cipher_suites = 9;</code>
     * @return string
     */
    public function getCipherSuites()
    {
        return $this->cipher_suites;
    }

    /**
     * Specify cipher suites, except for TLS 1.3.
     *
     * Generated from protobuf field <code>string cipher_suites = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setCipherSuites($var)
    {
        GPBUtil::checkString($var, True);
        $this->cipher_suites = $var;

        return $this;
    }

    /**
     * TLS Client Hello fingerprint (uTLS).
     *
     * Generated from protobuf field <code>string fingerprint = 11;</code>
     * @return string
     */
    public function getFingerprint()
    {
        return $this->fingerprint;
    }

    /**
     * TLS Client Hello fingerprint (uTLS).
     *
     * Generated from protobuf field <code>string fingerprint = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setFingerprint($var)
    {
        GPBUtil::checkString($var, True);
        $this->fingerprint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool reject_unknown_sni = 12;</code>
     * @return bool
     */
    public function getRejectUnknownSni()
    {
        return $this->reject_unknown_sni;
    }

    /**
     * Generated from protobuf field <code>bool reject_unknown_sni = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setRejectUnknownSni($var)
    {
        GPBUtil::checkBool($var);
        $this->reject_unknown_sni = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string master_key_log = 15;</code>
     * @return string
     */
    public function getMasterKeyLog()
    {
        return $this->master_key_log;
    }

    /**
     * Generated from protobuf field <code>string master_key_log = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setMasterKeyLog($var)
    {
        GPBUtil::checkString($var, True);
        $this->master_key_log = $var;

        return $this;
    }

    /**
     * Lists of string as CurvePreferences values.
     *
     * Generated from protobuf field <code>repeated string curve_preferences = 16;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCurvePreferences()
    {
        return $this->curve_preferences;
    }

    /**
     * Lists of string as CurvePreferences values.
     *
     * Generated from protobuf field <code>repeated string curve_preferences = 16;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCurvePreferences($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->curve_preferences = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string verify_peer_cert_by_name = 17;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVerifyPeerCertByName()
    {
        return $this->verify_peer_cert_by_name;
    }

    /**
     * Generated from protobuf field <code>repeated string verify_peer_cert_by_name = 17;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVerifyPeerCertByName($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->verify_peer_cert_by_name = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes ech_server_keys = 18;</code>
     * @return string
     */
    public function getEchServerKeys()
    {
        return $this->ech_server_keys;
    }

    /**
     * Generated from protobuf field <code>bytes ech_server_keys = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setEchServerKeys($var)
    {
        GPBUtil::checkString($var, False);
        $this->ech_server_keys = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ech_config_list = 19;</code>
     * @return string
     */
    public function getEchConfigList()
    {
        return $this->ech_config_list;
    }

    /**
     * Generated from protobuf field <code>string ech_config_list = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setEchConfigList($var)
    {
        GPBUtil::checkString($var, True);
        $this->ech_config_list = $var;

        return $this;
    }

    /**
     * Deprecated
     *
     * Generated from protobuf field <code>string ech_force_query = 20;</code>
     * @return string
     */
    public function getEchForceQuery()
    {
        return $this->ech_force_query;
    }

    /**
     * Deprecated
     *
     * Generated from protobuf field <code>string ech_force_query = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setEchForceQuery($var)
    {
        GPBUtil::checkString($var, True);
        $this->ech_force_query = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.SocketConfig ech_socket_settings = 21;</code>
     * @return \Xray\Transport\Internet\SocketConfig|null
     */
    public function getEchSocketSettings()
    {
        return $this->ech_socket_settings;
    }

    public function hasEchSocketSettings()
    {
        return isset($this->ech_socket_settings);
    }

    public function clearEchSocketSettings()
    {
        unset($this->ech_socket_settings);
    }

    /**
     * Generated from protobuf field <code>.xray.transport.internet.SocketConfig ech_socket_settings = 21;</code>
     * @param \Xray\Transport\Internet\SocketConfig $var
     * @return $this
     */
    public function setEchSocketSettings($var)
    {
        GPBUtil::checkMessage($var, \Xray\Transport\Internet\SocketConfig::class);
        $this->ech_socket_settings = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes pinned_peer_cert_sha256 = 22;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPinnedPeerCertSha256()
    {
        return $this->pinned_peer_cert_sha256;
    }

    /**
     * Generated from protobuf field <code>repeated bytes pinned_peer_cert_sha256 = 22;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPinnedPeerCertSha256($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->pinned_peer_cert_sha256 = $arr;

        return $this;
    }

}

