<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/version/config.proto

namespace Xray\App\Version;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.app.version.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string core_version = 1;</code>
     */
    protected $core_version = '';
    /**
     * Generated from protobuf field <code>string min_version = 2;</code>
     */
    protected $min_version = '';
    /**
     * Generated from protobuf field <code>string max_version = 3;</code>
     */
    protected $max_version = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $core_version
     *     @type string $min_version
     *     @type string $max_version
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Version\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string core_version = 1;</code>
     * @return string
     */
    public function getCoreVersion()
    {
        return $this->core_version;
    }

    /**
     * Generated from protobuf field <code>string core_version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCoreVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->core_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string min_version = 2;</code>
     * @return string
     */
    public function getMinVersion()
    {
        return $this->min_version;
    }

    /**
     * Generated from protobuf field <code>string min_version = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMinVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->min_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string max_version = 3;</code>
     * @return string
     */
    public function getMaxVersion()
    {
        return $this->max_version;
    }

    /**
     * Generated from protobuf field <code>string max_version = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMaxVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->max_version = $var;

        return $this;
    }

}

