<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/kcp/config.proto

namespace Xray\Transport\Internet\Kcp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.transport.internet.kcp.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 mtu = 1;</code>
     */
    protected $mtu = 0;
    /**
     * Generated from protobuf field <code>uint32 tti = 2;</code>
     */
    protected $tti = 0;
    /**
     * Generated from protobuf field <code>uint32 uplink_capacity = 3;</code>
     */
    protected $uplink_capacity = 0;
    /**
     * Generated from protobuf field <code>uint32 downlink_capacity = 4;</code>
     */
    protected $downlink_capacity = 0;
    /**
     * Generated from protobuf field <code>uint32 cwnd_multiplier = 5;</code>
     */
    protected $cwnd_multiplier = 0;
    /**
     * Generated from protobuf field <code>uint32 max_sending_window = 6;</code>
     */
    protected $max_sending_window = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $mtu
     *     @type int $tti
     *     @type int $uplink_capacity
     *     @type int $downlink_capacity
     *     @type int $cwnd_multiplier
     *     @type int $max_sending_window
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Kcp\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 mtu = 1;</code>
     * @return int
     */
    public function getMtu()
    {
        return $this->mtu;
    }

    /**
     * Generated from protobuf field <code>uint32 mtu = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMtu($var)
    {
        GPBUtil::checkUint32($var);
        $this->mtu = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 tti = 2;</code>
     * @return int
     */
    public function getTti()
    {
        return $this->tti;
    }

    /**
     * Generated from protobuf field <code>uint32 tti = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTti($var)
    {
        GPBUtil::checkUint32($var);
        $this->tti = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 uplink_capacity = 3;</code>
     * @return int
     */
    public function getUplinkCapacity()
    {
        return $this->uplink_capacity;
    }

    /**
     * Generated from protobuf field <code>uint32 uplink_capacity = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setUplinkCapacity($var)
    {
        GPBUtil::checkUint32($var);
        $this->uplink_capacity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 downlink_capacity = 4;</code>
     * @return int
     */
    public function getDownlinkCapacity()
    {
        return $this->downlink_capacity;
    }

    /**
     * Generated from protobuf field <code>uint32 downlink_capacity = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setDownlinkCapacity($var)
    {
        GPBUtil::checkUint32($var);
        $this->downlink_capacity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 cwnd_multiplier = 5;</code>
     * @return int
     */
    public function getCwndMultiplier()
    {
        return $this->cwnd_multiplier;
    }

    /**
     * Generated from protobuf field <code>uint32 cwnd_multiplier = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setCwndMultiplier($var)
    {
        GPBUtil::checkUint32($var);
        $this->cwnd_multiplier = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 max_sending_window = 6;</code>
     * @return int
     */
    public function getMaxSendingWindow()
    {
        return $this->max_sending_window;
    }

    /**
     * Generated from protobuf field <code>uint32 max_sending_window = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxSendingWindow($var)
    {
        GPBUtil::checkUint32($var);
        $this->max_sending_window = $var;

        return $this;
    }

}

