<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/finalmask/header/utp/config.proto

namespace GPBMetadata\Transport\Internet\Finalmask\Header\Utp;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ÿ
4transport/internet/finalmask/header/utp/config.proto,xray.transport.internet.finalmask.header.utp"
ConfigB¦
0com.xray.transport.internet.finalmask.header.utpPZAgithub.com/xtls/xray-core/transport/internet/finalmask/header/utpª,Xray.Transport.Internet.Finalmask.Header.Utpbproto3'
        , true);

        static::$is_initialized = true;
    }
}

