<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/stats/command/command.proto

namespace Xray\App\Stats\Command;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.app.stats.command.OnlineIPEntry</code>
 */
class OnlineIPEntry extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ip = 1;</code>
     */
    protected $ip = '';
    /**
     * Generated from protobuf field <code>int64 last_seen = 2;</code>
     */
    protected $last_seen = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ip
     *     @type int|string $last_seen
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Stats\Command\Command::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ip = 1;</code>
     * @return string
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     * Generated from protobuf field <code>string ip = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 last_seen = 2;</code>
     * @return int|string
     */
    public function getLastSeen()
    {
        return $this->last_seen;
    }

    /**
     * Generated from protobuf field <code>int64 last_seen = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastSeen($var)
    {
        GPBUtil::checkInt64($var);
        $this->last_seen = $var;

        return $this;
    }

}

