<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/stats/command/command.proto

namespace Xray\App\Stats\Command;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.app.stats.command.TrafficUserStat</code>
 */
class TrafficUserStat extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 uplink = 1;</code>
     */
    protected $uplink = 0;
    /**
     * Generated from protobuf field <code>int64 downlink = 2;</code>
     */
    protected $downlink = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $uplink
     *     @type int|string $downlink
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Stats\Command\Command::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 uplink = 1;</code>
     * @return int|string
     */
    public function getUplink()
    {
        return $this->uplink;
    }

    /**
     * Generated from protobuf field <code>int64 uplink = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUplink($var)
    {
        GPBUtil::checkInt64($var);
        $this->uplink = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 downlink = 2;</code>
     * @return int|string
     */
    public function getDownlink()
    {
        return $this->downlink;
    }

    /**
     * Generated from protobuf field <code>int64 downlink = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDownlink($var)
    {
        GPBUtil::checkInt64($var);
        $this->downlink = $var;

        return $this;
    }

}

