<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/stats/command/command.proto

namespace Xray\App\Stats\Command;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.app.stats.command.UserStat</code>
 */
class UserStat extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string email = 1;</code>
     */
    protected $email = '';
    /**
     * Generated from protobuf field <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
     */
    private $ips;
    /**
     * Generated from protobuf field <code>.xray.app.stats.command.TrafficUserStat traffic = 3;</code>
     */
    protected $traffic = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $email
     *     @type array<\Xray\App\Stats\Command\OnlineIPEntry>|\Google\Protobuf\Internal\RepeatedField $ips
     *     @type \Xray\App\Stats\Command\TrafficUserStat $traffic
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Stats\Command\Command::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string email = 1;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIps()
    {
        return $this->ips;
    }

    /**
     * Generated from protobuf field <code>repeated .xray.app.stats.command.OnlineIPEntry ips = 2;</code>
     * @param array<\Xray\App\Stats\Command\OnlineIPEntry>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xray\App\Stats\Command\OnlineIPEntry::class);
        $this->ips = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xray.app.stats.command.TrafficUserStat traffic = 3;</code>
     * @return \Xray\App\Stats\Command\TrafficUserStat|null
     */
    public function getTraffic()
    {
        return $this->traffic;
    }

    public function hasTraffic()
    {
        return isset($this->traffic);
    }

    public function clearTraffic()
    {
        unset($this->traffic);
    }

    /**
     * Generated from protobuf field <code>.xray.app.stats.command.TrafficUserStat traffic = 3;</code>
     * @param \Xray\App\Stats\Command\TrafficUserStat $var
     * @return $this
     */
    public function setTraffic($var)
    {
        GPBUtil::checkMessage($var, \Xray\App\Stats\Command\TrafficUserStat::class);
        $this->traffic = $var;

        return $this;
    }

}

