<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/finalmask/xicmp/config.proto

namespace GPBMetadata\Transport\Internet\Finalmask\Xicmp;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ž
/transport/internet/finalmask/xicmp/config.proto\'xray.transport.internet.finalmask.xicmp" 
Config

ip (	

id (B—
+com.xray.transport.internet.finalmask.xicmpPZ<github.com/xtls/xray-core/transport/internet/finalmask/xicmpª\'Xray.Transport.Internet.Finalmask.Xicmpbproto3'
        , true);

        static::$is_initialized = true;
    }
}

