<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/vless/outbound/config.proto

namespace Xray\Proxy\Vless\Outbound;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.proxy.vless.outbound.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.xray.common.protocol.ServerEndpoint vnext = 1;</code>
     */
    protected $vnext = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Xray\Common\Protocol\ServerEndpoint $vnext
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Vless\Outbound\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xray.common.protocol.ServerEndpoint vnext = 1;</code>
     * @return \Xray\Common\Protocol\ServerEndpoint|null
     */
    public function getVnext()
    {
        return $this->vnext;
    }

    public function hasVnext()
    {
        return isset($this->vnext);
    }

    public function clearVnext()
    {
        unset($this->vnext);
    }

    /**
     * Generated from protobuf field <code>.xray.common.protocol.ServerEndpoint vnext = 1;</code>
     * @param \Xray\Common\Protocol\ServerEndpoint $var
     * @return $this
     */
    public function setVnext($var)
    {
        GPBUtil::checkMessage($var, \Xray\Common\Protocol\ServerEndpoint::class);
        $this->vnext = $var;

        return $this;
    }

}

