<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/vmess/outbound/config.proto

namespace Xray\Proxy\Vmess\Outbound;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xray.proxy.vmess.outbound.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.xray.common.protocol.ServerEndpoint Receiver = 1;</code>
     */
    protected $Receiver = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Xray\Common\Protocol\ServerEndpoint $Receiver
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Vmess\Outbound\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xray.common.protocol.ServerEndpoint Receiver = 1;</code>
     * @return \Xray\Common\Protocol\ServerEndpoint|null
     */
    public function getReceiver()
    {
        return $this->Receiver;
    }

    public function hasReceiver()
    {
        return isset($this->Receiver);
    }

    public function clearReceiver()
    {
        unset($this->Receiver);
    }

    /**
     * Generated from protobuf field <code>.xray.common.protocol.ServerEndpoint Receiver = 1;</code>
     * @param \Xray\Common\Protocol\ServerEndpoint $var
     * @return $this
     */
    public function setReceiver($var)
    {
        GPBUtil::checkMessage($var, \Xray\Common\Protocol\ServerEndpoint::class);
        $this->Receiver = $var;

        return $this;
    }

}

